OpenApoc/OpenApoc

- data/LANGUAGES/LANGUAGES.XML
- data/LANGUAGES/STRINGS.XML
German language strings has been added to STRINGS.XML and LANGUAGE.XML
> German language strings

- framework/render/ogl_3_0_renderer.cpp
> GL30 renderer: Implement drawScaled

- OpenApoc.pro
- OpenApoc.vcxproj
- appveyor.yml
- data/UI/city/city.xml
- data/XCOMAPOC.XML
- framework/data.cpp
- game/apocresources/rawimage.cpp
- game/apocresources/rawimage.h
- game/city/cityview.cpp
- game/city/cityview.h
- game/general/difficultymenu.cpp
- game/tileview/tileview.cpp
Adds support for 'raw' images and loads isobord1 into a Form at the bottom of the city view. Only the <graphic> is in the form so far, so it's not interactive, and the event handling needs to be passed onto the Form if necessary to enable that.
A start on issue #40 at least
> Start the CityUI

- OpenApoc.pro
- OpenApoc.vcxproj
- data/UI/BASESCREEN.XML
- data/UI/OPTIONS.XML
- data/UI/UFOPAEDIA.XML
- data/UI/city/city.xml
- data/UI/city/infiltration.xml
- data/UI/city/score.xml
- data/XCOMAPOC.XML
- forms/control.cpp
- forms/control.h
- forms/form.cpp
- forms/graphic.cpp
- framework/framework.cpp
- framework/framework.h
- game/city/cityview.cpp
- game/city/cityview.h
- game/city/infiltrationscreen.cpp
- game/city/infiltrationscreen.h
- game/city/scorescreen.cpp
- game/city/scorescreen.h
- game/general/optionsmenu.cpp
- game/tileview/tileview.h
Start making the buttons do stuff.
Add a stub score/infiltration screen, wire up to 'options' screen (Not 'real' apoc options screen) and ufopaedia
> More CityUI work

- data/LANGUAGES/STRINGS.XML
working on the translation little by little
> Update Spanish translation

- README.md
Made this into a local branch (feel free to delete the previous).  This is what I had to do to get it to build with latest Ubuntu 14.04
> update build doc for Ubuntu 14.04.3

- data/UI/city/city.xml
- game/state/city/vehicle.cpp
- game/state/city/vehicle.h
- game/state/city/vehiclemission.cpp
- game/state/city/vehiclemission.h
- game/state/tileview/tile.cpp
- game/state/tileview/tile.h
- game/ui/base/vequipscreen.cpp
- game/ui/city/cityview.cpp
- Altitude and attack modes should work now.
- Added basic vehicle attack mission, makes it follow the target.
- Fixed vehicle accuracy value.
Still in TODO: evasive maneuvering, make attack modes matter, fix weapon range calculations.
> Gameplay: vehicle altitude and attack mission

- forms/ui.cpp
- forms/ui.h
- game/ui/debugtools/formpreview.cpp
- game/ui/debugtools/formpreview.h
New button in debugform menu that lets user reload form without restarting application.
> Reloading forms at runtime

- data/UI/INGAMEOPTIONS.XML
- data/UI/SAVEMENU.XML
- game/state/savemanager.cpp
- game/state/savemanager.h
- game/ui/general/ingameoptions.cpp
- game/ui/general/savemenu.cpp
- game/ui/general/savemenu.h
Delete save game in ingamemenu that (suprise) deletes saved game.
> Delete save game

- data/common_patch/gamestate.xml
- data/ui/battle/battle.xml
- forms/scrollbar.cpp
- forms/scrollbar.h
- game/state/aequipment.cpp
- game/state/aequipment.h
- game/state/agent.cpp
- game/state/battle/battle.cpp
- game/state/battle/battle.h
- game/state/battle/battledoor.h
- game/state/battle/battleexplosion.cpp
- game/state/battle/battlehazard.cpp
- game/state/battle/battlehazard.h
- game/state/battle/battleitem.cpp
- game/state/battle/battlemappart.cpp
- game/state/battle/battlemappart.h
- game/state/battle/battleunit.cpp
- game/state/battle/battleunit.h
- game/state/battle/battleunitmission.cpp
- game/state/gamestate_serialize.xml
- game/state/rules/aequipment_type.h
- game/state/rules/damage.h
- game/state/tileview/collision.cpp
- game/state/tileview/tile.h
- game/ui/battle/battleview.cpp
- game/ui/battle/battleview.h
- tools/extractors/extract_agent_equipment.cpp
- explosives priming interface (only real time style for now)
- fixes to collapsible map, now hopefully no more infinite loops and hanging scenery
- collapsing map parts now spawn smoke
- flying units dying now properly fall
- implemented brainsucker launcher (can also create "launcher" weapons that prime their payload and throw it out)
- fixed alien gas dealing terrain damage (vanilla files bug?)
- fixed smoke producing hit sound
> priming explosives + fixes (mostly to collapsible map)

- game/state/battle/ai.cpp
- game/state/battle/ai.h
- game/state/battle/battle.cpp
- game/state/battle/battle.h
- game/state/battle/battlemap.cpp
- game/state/battle/battlemap.h
- game/state/battle/battlemappart.cpp
- game/state/battle/battlemappart.h
- game/state/battle/battlemapsector.h
- game/state/battle/battleunit.cpp
- game/state/battle/battleunit.h
- game/state/battle/battleunitmission.cpp
- game/state/battle/battleunitmission.h
- game/state/city/vehiclemission.cpp
- game/state/gamestate_serialize.xml
- game/state/tileview/pathfinding.cpp
- game/state/tileview/tile.cpp
- game/state/tileview/tile.h
- game/state/tileview/tileobject_battlemappart.cpp
- game/ui/tileview/battletileview.cpp
- tools/extractors/extract_battlescape_map.cpp
- when pathfinding over long distances in battlescape, units now use losblocks as guidance in order to make pathfinding over any distance and any complexity a trivial task
> pathfinding using los blocks

- data/forms/battle/hidden.form
- game/state/aequipment.cpp
- game/state/aequipment.h
- game/state/battle/ai/tacticalaivanilla.cpp
- game/state/battle/ai/unitai.cpp
- game/state/battle/ai/unitai.h
- game/state/battle/ai/unitaidefault.cpp
- game/state/battle/ai/unitaihelper.cpp
- game/state/battle/ai/unitaihelper.h
- game/state/battle/ai/unitailowmorale.cpp
- game/state/battle/ai/unitaivanilla.cpp
- game/state/battle/ai/unitaivanilla.h
- game/state/battle/battle.cpp
- game/state/battle/battle.h
- game/state/battle/battleexplosion.cpp
- game/state/battle/battleunit.cpp
- game/state/battle/battleunit.h
- game/state/city/city.cpp
- game/state/city/city.h
- game/state/city/vehicle.cpp
- game/state/gamestate_serialize.xml
- game/state/tileview/pathfinding.cpp
- game/state/tileview/tileobject_battleunit.cpp
- game/ui/battle/battleview.cpp
- game/ui/tileview/battletileview.cpp
- game/ui/tileview/battletileview.h
- tools/extractors/docs/tb.txt
- Hidden enemy turns
- Cloaking for units
- AI action "Fallback"
> Hidden enemy turns, Cloaking, Minor AI improvements

- data/forms/battle/battle_rt_tab1.form
- data/forms/battle/battle_tb_tab1.form
- game/ui/battle/battleview.cpp
> fixed buggy item ui

- game/state/stateobject.h
This is what I get for trying to rejig the builds at the same time
- stuff that *Happened* to work on my local machine don't get tested
> Build fix for linux build fix

- README.md
- TODO.md
This pull request cleans up the format, order, and parsability of the README and makes it more concise.
> Format and clean up README

- forms/control.cpp
- forms/control.h
- game/ui/debugtools/formpreview.cpp
> Control's mouse checking. Fix crash on FormPreview screen

- game/state/city/agentmission.cpp
- game/state/city/agentmission.h
- game/state/gamestate.cpp
- game/state/tileview/pathfinding.cpp
- game/state/tileview/tile.h
- game/ui/tileview/battletileview.cpp
- game/ui/tileview/citytileview.cpp
- fixed bug in agent pathfinding (note that on Novice difficulty, map of
vanilla city itself is bugged and until it's fixed manually, you will
still see that agents can't go to certain places because tube parts are
misaligned)
> agent pathfinding fix

- README_HOTKEYS.txt
- data/common_patch/gamestate/organisations.xml
- data/forms/recruitscreen.form
- forms/listbox.cpp
- forms/listbox.h
- game/state/gamestate.cpp
- game/state/gamestate_serialize.xml
- game/state/shared/organisation.cpp
- game/state/shared/organisation.h
- game/ui/CMakeLists.txt
- game/ui/base/basescreen.cpp
- game/ui/base/basestage.cpp
- game/ui/base/recruitscreen.cpp
- game/ui/base/recruitscreen.h
- game/ui/base/researchscreen.cpp
- game/ui/base/transactionscreen.cpp
- game/ui/base/transactionscreen.h
- game/ui/gameui.vcxproj
- game/ui/gameui.vcxproj.filters
- game/ui/general/aequipscreen.cpp
- game/ui/general/aequipscreen.h
- game/ui/tileview/battleview.cpp
- game/ui/tileview/cityview.cpp
- library/xorshift.h
- tools/extractors/docs/video.txt
- tools/extractors/extract_organisations.cpp
- recruiting and firing agents
- hirable agent types assigned to orgs
- listbox properly de-parenting and de-selecting
- transaction screen having static base captions
- proper magic arrow direction in all screens (away from mouse)
>  recruiting and firing agents, fixes

- data/common_patch/gamestate/ufo_incursions.xml
- data/forms/city/tab2.form
- game/state/CMakeLists.txt
- game/state/battle/battle.cpp
- game/state/city/vehicle.cpp
- game/state/city/vehicle.h
- game/state/city/vehiclemission.cpp
- game/state/city/vequipment.cpp
- game/state/city/vequipment.h
- game/state/gamestate.cpp
- game/state/gamestate.h
- game/state/gamestate.vcxproj
- game/state/gamestate.vcxproj.filters
- game/state/gamestate_serialize.h
- game/state/gamestate_serialize.xml
- game/state/rules/city/ufomissionpreference.cpp
- game/state/rules/city/ufomissionpreference.h
- game/state/tilemap/pathfinding.cpp
- game/state/tilemap/tileobject_vehicle.cpp
- game/ui/base/transactionscreen.cpp
- game/ui/components/basegraphics.cpp
- game/ui/tileview/cityview.cpp
- game/ui/tileview/cityview.h
- tools/extractors/main.cpp
- vehicle weapon disable controls
- vehicle weapon ammo display
- groundwork for proper ufo incusrions and missions done
- vehicles properly checking los when deciding wether to maneuver around
target
- vehicles properly aiming at ground vehicles's centre
- vehicles fire guided munitions when not in firing arc
- vehicles check vertical firing arcs properly
- one case of vehicles deadlocking fixed
- loot no longer stored if no containment at all present on vehicle
> weapon controls, ufo incursions, fixes

- README_HOTKEYS.txt
- game/state/city/city.cpp
- game/state/city/city.h
- game/state/city/vehiclemission.cpp
- game/state/city/vehiclemission.h
- game/state/tilemap/pathfinding.cpp
- road vehicles now pathfind using road segments which tremendously
speeds up the algorithm
- need playtesting (seems to bug out with broken roads)
> improved pathfinding for road vehicles

- README_HOTKEYS.txt
- game/state/battle/battlemappart.cpp
- game/state/battle/battlemappart.h
- game/state/city/base.cpp
- game/state/city/city.cpp
- game/state/city/city.h
- game/state/city/scenery.cpp
- game/state/city/scenery.h
- game/state/city/vehicle.cpp
- game/state/gamestate.cpp
- game/state/gamestate.h
- game/state/gamestate_serialize.xml
- game/state/rules/supportedmappart.cpp
- game/state/rules/supportedmappart.h
- game/state/shared/agent.cpp
- game/state/shared/agent.h
- game/state/shared/organisation.cpp
- game/ui/tileview/citytileview.cpp
- game/ui/tileview/citytileview.h
- game/ui/tileview/cityview.cpp
- tools/extractors/extract_city_map.cpp
- tools/extractors/extract_city_scenery.cpp
- tools/extractors/extract_facilities.cpp
- city scenery repair
- vehicle repair
- agent healing
- city collapse algorithm improvements
> collapse improvements, repair and healing

- framework/sound/sdlraw_backend.cpp
also be more verbose about selected audio device ;)
> fix audio sample conversion issues in some systems

- data/forms/researchscreen.form
- forms/listbox.cpp
- game/OpenApoc.vcxproj.user
- game/state/city/base.h
- game/state/city/research.cpp
- game/state/city/research.h
- game/ui/base/researchscreen.cpp
- game/ui/base/researchscreen.h
- game/ui/components/controlgenerator.cpp
- game/ui/components/controlgenerator.h
- tools/extractor.vcxproj.user
- created two separate lists for small and large labs;
- added quantity number for lab icon;
- the state will remember selected lab for each base separately.
> refactoring Researchscreen

- game/ui/base/transactionscreen.cpp
> fixes vehicles being bought twice in transaction screen

- forms/listbox.cpp
fixed listbox rendering as described the issue #171
> fix listbox render

- game/state/rules/city/vehicletype.h
Fixes getMaxPassengers not accounting for passenger module equipment (see issue #253)
> fix passenger modules

- game/ui/tileview/cityview.cpp
> fixed the button's "attack building" bug

- data/forms/recruitscreen.form
- data/forms/sheet_personel_stats.form
- forms/graphicbutton.cpp
- forms/scrollbar.cpp
- game/state/shared/agent.cpp
- game/state/shared/agent.h
- game/ui/base/recruitscreen.cpp
- game/ui/base/recruitscreen.h
- game/ui/components/controlgenerator.cpp
- game/ui/general/aequipscreen.cpp
- added skill label for scientists;
- added forms attribute "largechange" to scroll and "scrolllarge" to graphicbutton.
> refactoring Recruitscreen

- game/state/city/base.cpp
fixed issue #256 "Money is not recovered on destroying a room that is under construction"
> fixed destroyFacility()

- game/ui/base/transactionscreen.cpp
fixed issue #267 "Can't move scroll bar of some sell \ buy position by mouse"
> fixed the TransactionControl's horizontal scroll bar

- game/state/city/vehicle.cpp
- game/state/gamestate.cpp
- game/state/gamestate.h
fixed issue #274 "Game crash/use-after-free of Vehicle in Vehicle::update() with DepartToSpace mission"
BTW need a refactoring actually
> workaround for vehicle update & die

- game/ui/ufopaedia/ufopaediacategoryview.cpp
- game/ui/ufopaedia/ufopaediacategoryview.h
fixed issue #250 "We need add hotkeys in to ufopedia"
> added hotkeys to ufopaedia

- game/ui/tileview/citytileview.cpp
- game/ui/tileview/citytileview.h
- Reduced the number of calculations for interpolated palette.
- Also decreased the number of allocations/deallocations.
> Reduced the number of calculations for the cityview interpolated palette

- data/forms/city/agentassignment.form
- game/ui/city/alertscreen.cpp
- game/ui/components/agentassignment.cpp
Implemented sending a fleet of vehicles or group of agents to exterminate aliens.
> AlertScreen extermination implemented

- data/forms/city/agentassignment.form
- game/state/shared/agent.cpp
- fixed issue #253 "Now any number of agents can be added to a craft, regardless of number of passenger modules!"
- pixelperfection for AgentAssignment
> fixed enterVehicle()

- game/ui/city/buildingscreen.cpp
fixed issue #285 "Raiding a destroyed building should be prohibited"
> Raiding a destroyed building should be prohibited

- game/state/battle/battle.cpp
- game/state/city/vehicle.cpp
- fixed issue #301 "Completing a "Live Alien Spotted" Mission does not clear the red circle on city map"
- fixed vehicle's bio storage calculation
> fixed finishBattle()

- game/state/gamestate.cpp
- game/state/gamestate.h
- game/ui/base/transactionscreen.cpp
fixed issues:
- #314 "Vehicles still in base after selling until time passed" 
- #315 "Vehicle ID Mismatch and CTD after selling manufactured craft and save/load"
> fixed vehicles-zombies

- game/state/city/base.cpp
- game/ui/base/recruitscreen.cpp
fixed issue #322 "Cannot fill living quarters on new bases"
> fixed living quarters counting

- game/state/city/vehicle.cpp
- game/state/city/vehicle.h
- game/state/city/vehiclemission.cpp
- game/state/gamestate.cpp
- game/state/shared/organisation.cpp
- game/state/tilemap/tilemap.cpp
- game/state/tilemap/tilemap.h
fixed issue #255 "Emergency Vehicles do not pick up crashed road vehicles".
> fixed the mission RecoverVehicle

- data/forms/city/score.form
- data/forms/city/sheet_finance.form
- data/forms/city/sheet_score.form
- game/state/city/vehiclemission.cpp
- game/ui/city/scorescreen.cpp
- game/ui/city/scorescreen.h
- game/ui/tileview/cityview.cpp
- game/ui/tileview/cityview.h
> implemented the ScoreScreen

- game/state/city/vehicle.h
fixed issue #341 "Problem with "Out of Fuel" Road Vehicle Recovery"
Chance to recover vehicle increases to 100%.
> fixed the vehicle's recovery issue

- game/ui/tileview/cityview.cpp
In case if the research or manufacturing or facility completed, the game should be paused.
> always set pause after research or facility completed

- data/forms/sheet_agent_stats.form
- data/forms/sheet_vehicle_item.form
- forms/control.cpp
- forms/forms_enums.h
- forms/textedit.cpp
- forms/textedit.h
- game/ui/base/basescreen.cpp
- game/ui/base/vequipscreen.cpp
- game/ui/general/aequipscreen.cpp
- game/ui/general/agentsheet.cpp
- game/ui/general/vehiclesheet.cpp
for
https://github.com/OpenApoc/OpenApoc/issues/323
https://github.com/OpenApoc/OpenApoc/issues/179
Agent can be renamed on equip screen
Vehicle can be renamed on equip screen
> editable agent / craft name

- data/forms/city/tab3.form
- data/forms/city/tab4.form
- data/forms/city/tab5.form
- data/forms/city/tab6.form
- data/forms/city/tab7.form
- data/forms/city/tab8.form
- game/ui/tileview/cityview.cpp
display selected organisations relation to X-COM
display selected Vehicle name and owner (https://github.com/OpenApoc/OpenApoc/issues/328)
display Physicists project progress
display Engineers project progress
display Biochemists project progress
display Soldiers rank and training assignment
> cityscape UI text

- README.md
This pull request does a number of cosmetic fixes to the README, including the following:
* Properly spaced headers
* No trailing whitespace
* Consistently formatted lists
* Removed underscores in headers
* Fix the grammar in the tweet button
* Remove stray html breaks.
* Further grammar fixes
* Upgraded a bunch of URLs to HTTPS and fixed a broken link
> Clean README formatting

- game/state/city/vehicle.cpp
- game/state/shared/projectile.cpp
For some reason vehicle tileobjects are null pointers. Added some checks to prevent game from crashing.
> Null ptr checks

- game/state/battle/battle.cpp
Added check which only makes current player's units to run and kneel.
Fixes #401
> Fix to Agent tried to move walking without a standing/flying body state #401

- game/state/rules/battle/battlemap.cpp
Added check that base exists in the building owned by X-Com.
> No base error fixed #400

- framework/framework.cpp
- game/state/gamestate.cpp
- game/ui/general/ingameoptions.cpp
> add option to seed rng on game start

- data/forms/cheatoptions.form
- data/forms/ingameoptions.form
- forms/scrollbar.cpp
- forms/transactioncontrol.cpp
- framework/configfile.cpp
- framework/configfile.h
- framework/framework.cpp
- game/ui/CMakeLists.txt
- game/ui/gameui.vcxproj
- game/ui/gameui.vcxproj.filters
- game/ui/general/cheatoptions.cpp
- game/ui/general/cheatoptions.h
- game/ui/general/ingameoptions.cpp
- library/strings.cpp
- library/strings.h
Adds a cheat menu accessible via de ingame options. Only the following are implemented:
* Give all research
* Modify funds
* Org relationship (chaos, all hostile, all friendly, utopia)
> Cheat menu

- data/forms/cheatoptions.form
- game/state/battle/battleunit.cpp
- game/state/city/vehicle.cpp
- game/state/city/vequipment.cpp
- game/state/rules/battle/battlemap.cpp
- game/state/shared/aequipment.cpp
- game/state/shared/agent.cpp
- game/ui/city/buildingscreen.cpp
- game/ui/general/cheatoptions.cpp
Implements the following cheats:
* Damage inflicted multiplier
* Damage received multiplier
* Stat growth multiplier
* Infinite ammo
* Hostiles multiplier
> Implement cheats

- game/state/city/vehicle.cpp
- game/state/city/vehicle.h
- game/state/tilemap/tilemap.h
* Fixes vehicles becoming stuck when auto-facing towards enemies
* Fixes ground vehicles consuming fuel when idle (#372)
> Vehicle fixes

- .gitignore
- game/state/city/agentmission.cpp
- game/state/city/agentmission.h
- game/state/city/building.cpp
- game/state/city/building.h
- game/state/city/vehicle.cpp
- game/state/city/vehiclemission.cpp
- game/state/city/vehiclemission.h
- game/state/gameevent.cpp
- game/state/gameeventtypes.h
- game/state/gamestate.cpp
- game/state/gamestate.h
- game/state/gamestate_serialize.xml
- game/state/shared/agent.cpp
- game/ui/city/alertscreen.cpp
- game/ui/general/difficultymenu.cpp
- game/ui/tileview/cityview.cpp
- game/ui/tileview/cityview.h
- tests/test_serialize.cpp
Merges #408 and adds support for multiple vehicles and agents on foot.
Should also work if:
* The vehicle/agent was destroyed while traveling
* The vehicle/agent changed mission while traveling
> Pause game when x-com arrives for investigation

- game/state/gamestate_serialize.xml
Adds missing entry in gamestate_serialize.xml (fixes #461)
> serialize InvestigateBuilding VehicleMission type

- game/ui/tileview/citytileview.cpp
Prevents crash to desktop as described in #460
> fix map rendering with null targetVehicle in AttackVehicle mission

- data/difficulty4_patch/gamestate/cities/CITYMAP_HUMAN/buildings.xml
#485 Added missing warehouse and changed the layouts to correct one.
> Fix wrong warehouse layouts on hard difficulty

- data/difficulty2_patch/gamestate/cities/CITYMAP_HUMAN/buildings.xml
- data/difficulty3_patch/gamestate/cities/CITYMAP_HUMAN/buildings.xml
- data/difficulty4_patch/gamestate/cities/CITYMAP_HUMAN/buildings.xml
Fixed following buildings:
Easy
WH9
Medium
WH3
Oliver Twist Block
Hard
Campesino
> Fix layout on easy, medium and hard difficulty

- game/state/battle/battle.cpp
- game/state/city/building.cpp
- game/state/gamestate_serialize.xml
- game/state/rules/battle/battlemap.cpp
- game/state/shared/agent.h
Fixes alien movement roll triggering base defense missions without aliens actually moving
Hopefully fixes base defense crashing #446 ?
> Base defense fixes

- data/common_patch/gamestate/ufopaedia.xml
- tools/extractors/extract_agent_types.cpp
> Fix chrysalis autopsy showing megaspawn picture

- framework/data.cpp
> Don't try to create dir if output image file is in the PWD

- forms/label.cpp
- forms/label.h
- forms/transactioncontrol.cpp
- game/ui/base/recruitscreen.cpp
- game/ui/components/controlgenerator.cpp
- library/CMakeLists.txt
- library/colour.cpp
- library/colour.h
- library/library.vcxproj
- library/strings.cpp
- library/strings.h
Adds support for tinted labels:
* Recruit screen
* Lab screen
* Buy and sell screen (hostile manufacturer)
> Tinted label

- game/state/battle/battle.cpp
- game/state/gameeventtypes.h
- game/state/gamestate.cpp
- game/state/gamestate.h
- game/state/gamestate_serialize.xml
> Post mission event fix

- library/colour.cpp
- tests/CMakeLists.txt
- tests/test_colour.cpp
> Fix hexcode triplet decoding in colour.cpp

- forms/listbox.cpp
Fixes scrollbar auto-resizing for listboxes that contain items with variable sizes (Fixes #515)
> fix scroll resizing for listboxes with variable-size items

- OpenApoc.sln
- data/data.vcxproj
- framework/luaframework.h
- tools/code_generators/luagamestate_support_gen/main.cpp
> Msvc fixes

- data/forms/battle/battle.form
- data/forms/battle/battle_rt_tab2.form
- data/forms/battle/battle_tb_tab2.form
- game/ui/tileview/battleview.cpp
- game/ui/tileview/battleview.h
> Refactor battle view

- game/state/tilemap/collision.cpp
- game/state/tilemap/tileobject_battleunit.cpp
> Fix out of bounds voxel indexing

- game/state/battle/battlemappart.cpp
> fix crash while iterating and applying falling damage

- data/forms/city/overlay.form
- forms/checkbox.cpp
- forms/control.cpp
- forms/control.h
- forms/graphicbutton.cpp
- forms/radiobutton.cpp
- forms/scrollbar.cpp
- forms/textbutton.cpp
- forms/textedit.cpp
> Prevent clickthrough on overlapping controls

- framework/configfile.cpp
Really smart compilers and lto may recognise that in some tests/tools the
option object may not be used and has no side effects, so DCE it completely.
> Make unrecognised cmdline options just warn instead of fatal error

- framework/logger.cpp
- framework/logger.h
This should speed things up a fair bit in some cases with excess logging
disabled
> Logging fixes

- data/forms/sheet_agent_stats.form
- game/ui/general/agentsheet.cpp
Fixes #553 
This will close my feature request
Fixes #551 
Optional extra (see below)
Hello World! This is my very first PR at GitHub.
I attach some screenshots for demonstration, but it's with old savegame file, so it has some version incompatibility bugs and simple doesn't fixed bugs.
> Adding tooltips with agent stats to Agent Equipment screen

- framework/logger.cpp
It's possible multiple threads /could/ cause the logger to be inited multiple
times - this should avoid that.
> Make the logger init check atomic

- data/scripts/openapoc_base.lua
- framework/luaframework.cpp
- library/xorshift.h
- tests/test_rng.cpp
The getState/setState methods are really internal-state-dump/recovery rather
than seeding, so add a seed() method to do exactly that
> Add a seed(uint64_t) method to the Xorshift RNG and use that in lua

- framework/physfs_fs.cpp
Might make debugging loading issues easier?
> Add a log output showing the working dir when initialising the filesystem

- framework/framework.cpp
Should give some actual randomness to the starting & order of played
music
> Seed the jukebox shuffle RNG with time

- game/ui/tileview/battletileview.cpp
> Avoid div0 calculating hidden movement

- tools/dump_everything/dump_everything.cpp
This has been broken for a while, as it's not built by default
> Fix build of dump_everything tool

- framework/render/gl20/ogl_2_0_renderer.cpp
- framework/render/gles30_v2/ogles_3_0_renderer_v2.cpp
Some objects (like the ControlGenerator) keep references to Images in global
static scope, so end up being destructed at process termination time - after
the renderer has already been destroyed.
This then causes a use-after-free trying to callback into the renderer to
cleanup it's internal data.
Workaround this by keeping a static flag if that renderer is still alive.
I don't like this 'fix', as it'll break if there's ever more than 1 renderer
of each type constructed in the process lifetime, and things shouldn't keep
static handles to Images anyway, but this avoids the issue in the short-term
> Workaround crashes on exit due to use-after-free of renderer

- game/ui/tileview/cityview.cpp
Should allow easier progress is debugging issues with things gated behind
specific UFOs
> Randomize which UFOs are generated when generating crashed UFOs

- forms/listbox.cpp
- forms/multilistbox.h
- framework/render/gl20/ogl_2_0_renderer.cpp
- framework/render/gles30_v2/gleswrap_gles3.h
- game/state/battle/ai/tacticalaivanilla.cpp
- game/state/battle/battlemappart.cpp
https://scan.coverity.com/projects/jonnyh-openapoc
A few look like "real" bugs
> Fix some coverity-noticed issues

- game/state/city/scenery.cpp
This should avoid a crash caused by Vehicle::applyDamage() possibly destroying
a vehicle, invaldating the current TileObject iterator on Tile::ownedObjects.
> Handle invalidating Tile::ownedObject iterators in Scenery::updateFalling

- README.md
- appveyor-dev.yml
- appveyor.yml
- framework/configfile.cpp
- framework/configfile.h
- install/windows/installer.nsi
- tools/CMakeLists.txt
- tools/launcher/CMakeLists.txt
- tools/launcher/launcherwindow.cpp
- tools/launcher/launcherwindow.h
- tools/launcher/launcherwindow.ui
- tools/launcher/main.cpp
- tools/travis-scripts/build_prepare_linux.sh
Some options are hard to setup in-game (IE things that pretty much require a renderer restart, like screen size/fullscreen options), and gives a nicer UI to select the CD / Data paths.
Going forward I intend to make the 'mods' tab actually do something :)
> Add a launcher to set some options

- data/forms/cheatoptions.form
- game/state/gametime.h
- game/ui/general/cheatoptions.cpp
> Add cheat option to go forward 1 day or week

- framework/CMakeLists.txt
- framework/data.cpp
- framework/sampleloader/wavsound.cpp
- framework/sampleloader_interface.h
- framework/sound.h
Only supports u8/s16_lsb mono WAV files
> Initial WAV sample loading

- appveyor-dev.yml
- appveyor.yml
Might workaround cmake failures in vcpkg update?
> Update vcpkg to 2019.10

- .gitignore
Clearly no need to version logfile
> Ignore for log file

- game/state/battle/ai/unitaidefault.cpp
> Agents do not auto attack civilians anymore

- game/state/city/base.cpp
- game/state/gamestate.h
- game/state/gamestate_serialize.xml
- game/ui/city/basebuyscreen.cpp
- game/ui/tileview/cityview.cpp
- game/ui/tileview/cityview.h
> Refresh the base icons after losing a base

- README.md
> fix of readme windows building instructions

- game/ui/tileview/cityview.cpp
> Don't commence investigation if agents are called off.

- game/state/city/vehicle.cpp
- game/state/city/vehiclemission.cpp
Identified and related to #332, might as well fix it.
> Fix a couple of CDTs during vehicle combat.

- game/state/tilemap/tilemap.cpp
Related to https://github.com/OpenApoc/OpenApoc/issues/364#issuecomment-513475035
> Don't add smoke to a carried vehicle.

- game/state/battle/battlemappart.cpp
> Fix a CTD while iterating over a changing set.

- game/state/city/city.cpp
> Notify road segment of a road tile repair to restore its passability.

- game/ui/base/buyandsellscreen.cpp
- game/ui/base/transferscreen.cpp
> Allow transactions which do not increase excess of living/storage/containment space.

- game/state/city/scenery.cpp
> Allow repair of non-collapsed scenery.

- game/state/city/vehicle.cpp
> Make sure vehicle stops falling in some rare cases.

- game/state/city/vehicle.cpp
> Drop carried vehicle when dying.

- framework/fs.h
- framework/physfs_fs.cpp
- game/state/gamestate.cpp
> Add support for appending game state from a directory.

- game/ui/base/researchselect.cpp
> Clear unselected topic's background in research selection form.

- data/common_patch/gamestate/research.xml
- data/common_patch/gamestate/ufopaedia.xml
- game/ui/tileview/cityview.cpp
- tools/extractors/extract_buildings.cpp
> Fix research unlock for Alien Dimension and alien building access.

- tools/extractors/extract_agent_equipment.cpp
Adjusts toxigun, plasma, and laser damage type not to detonate poppers.
Resolves #744.
> Make toxigun, plasma, and laser damage non-violent.

- forms/control.cpp
Fixes a bogus check preventing tooltips from showing up.
> Fix tooltip loading.

- framework/configfile.cpp
- framework/configfile.h
Fixes log strings for options of floating point type.
> Fix dumping of floating point options to log.

- framework/trace.cpp
Adds names for pool's threads on Windows (visible in debugger).
> Add support for thread naming on Windows.

- .vs/launch.vs.json
Adds default settings for DataExtractor utility to launch and debug it in Visual Studio.
> Add VS launch settings for DataExtractor.

- game/state/city/vehicle.cpp
Resolves issues with vehicles becoming stuck mid-air.
Related to #682.
> Prevent vehicle velocity from dropping to zero when maneuvering.

- game/state/city/vehiclemission.cpp
- game/state/city/vehiclemission.h
> Allow large vehicles moving into tiles occupied by themselves.

- forms/textedit.cpp
- game/ui/base/basescreen.cpp
- game/ui/base/recruitscreen.cpp
- game/ui/base/transactionscreen.cpp
- game/ui/base/vequipscreen.cpp
- game/ui/battle/battlebriefing.cpp
- game/ui/battle/battledebriefing.cpp
- game/ui/battle/battleprestart.cpp
- game/ui/city/bribescreen.cpp
- game/ui/city/scorescreen.cpp
- game/ui/general/aequipscreen.cpp
- game/ui/general/messagebox.cpp
- game/ui/general/notificationscreen.cpp
- game/ui/skirmish/skirmish.cpp
- game/ui/tileview/battleview.cpp
> Support keypad enter button.

- data/forms/researchscreen.form
- forms/listbox.cpp
> Fix large lab assignment UI.

- game/state/battle/battle.cpp
- game/state/city/vehiclemission.cpp
- game/ui/tileview/cityview.cpp
> Go-to-base order in Alien dimension now sends vehicles to a portal.

- game/ui/general/agentsheet.cpp
Fix text error in #583 in Speed tooltip.
> fix Speed format string in tolltips

- game/ui/base/recruitscreen.cpp
> Fix CTD on the Hire/Fire Staff button

- game/ui/tileview/cityview.cpp
Cause : invalid type specifier in message box format string,
> Fix crash on manufacture completed event.

- game/ui/tileview/battleview.cpp
Interrupt player's battleunits missions on HostileSpotted event in TB
> Interrupt player's battleunits missions on HostileSpotted event in TB

- game/state/battle/battleunit.cpp
- game/state/gameevent.cpp
- game/state/gameeventtypes.h
- game/state/shared/aequipment.cpp
> Generate notification when agent is out of ammo.

- game/state/city/building.cpp
- game/state/city/vehiclemission.cpp
- game/state/gameevent.cpp
I opened a new one because I messed up the git squash in the first pull request.
> Destroy empty bases when attacked

- game/ui/tileview/cityview.cpp
Fixes #978 . 
Quick access button relied on selected agent. Moved repeated code into anonymous namespace helper function.
> UI: Find research facility even if no agent is selected

- game/ui/tileview/cityview.cpp
> Fix crash due to invalid cargo log format

- data/forms/city/diplomatic_treaty.form
- game/state/gameeventtypes.h
- game/state/gamestate.cpp
- game/state/gamestate_serialize.xml
- game/state/shared/organisation.cpp
- game/state/shared/organisation.h
- game/ui/CMakeLists.txt
- game/ui/city/bribescreen.cpp
- game/ui/city/diplomatictreatyscreen.cpp
- game/ui/city/diplomatictreatyscreen.h
- game/ui/tileview/cityview.cpp
- tools/extractors/extract_organisations.cpp
Organisations now will demand money if your relationship changed drastically. Also adjusted bribe costs based on OG formula.
> Implement diplomatic rift event

- data/forms/city/alert.form
Added Alert header to Alert screen
> Added Alert header to Alert screen - Update alert.form

- data/forms/city/alert.form
Added header to alert screen Update alert.form fixed error and position
> Added header to alert screen Update alert.form fixed error and position

- .github/workflows/cmake.yml
- .github/workflows/lint.yml
- framework/framework.cpp
Now travis-ci isn't free it makes sense to move over
> Use github actions for linux CI builds

- game/state/gameeventtypes.h
- game/state/gamestate.cpp
- game/state/gametime.cpp
- game/state/gametime.h
- game/ui/general/cheatoptions.cpp
- game/ui/tileview/cityview.cpp
- game/ui/tileview/cityview.h
As in title
I've also included a call to an hook for LUA script that i don't think exists (but i've added it for simmetry with end of week handling)
> Nightly Score & Finance screen

- game/state/gamestate.cpp
Trailing space in comment? Thought I'd fixed this?
> Format gamestate.cpp

- framework/video/smk.cpp
- Fix stutter by on-demand loading of additional audio frames when current frame has less remaining samples than number requested by audio backend.
> Fix audio stutter in intro/outro video

- game/state/battle/battleunit.cpp
- game/ui/tileview/battleview.cpp
- Fix #1046: CTD when psi-controlled unit dies (iterating over container while modifying it)
- Fix crash in debug on bad formatting argument
> Crash fixes

- README.md
Updated documentation by build instructions for newer macOS.
> Add macOS build documentation

- .github/workflows/lint.yml
- appveyor-dev.yml
- appveyor.yml
Fix appveyor build and github lint workflow.
Tested appveyor and lint workflow script, both are working.
Should be able to retry the other PRs after merging this one.
> Fix build/lint: Update github workflow and appveyor yaml file

- game/ui/base/recruitscreen.cpp
This should fix the issue #1066 by ensuring that scientists get removed from their lab before the transfer.
> Fixes transfers on the recruit screen - Fix #1066

- .github/workflows/lint.yml
Attempt to fix linting for releases
> Make lint work on releases

- README.md
This PR is a slight grammar cleanup in the readme. Addresses #1125. I didn't hear any feedback yet for that issue so I figured I'd just go ahead and drop this.
> Grammar cleanup

- game/state/city/scenery.cpp
Fix #749 
Fix reset destroyed state of tile
> Fix Issue #749

- game/state/city/vehicle.h
- game/state/city/vehiclemission.cpp
- game/ui/city/alertscreen.cpp
- tools/extractors/common/vehicle.h
> Fix Investigator Count < 0

- game/ui/city/baseselectscreen.cpp
Autoscroll now works in the base buy screen like the original game!
> Add autoscroll to the base buy screen

- forms/scrollbar.cpp
- framework/options.cpp
- framework/options.h
- game/ui/general/ingameoptions.cpp
Addresses #1202. 
Adds an option to disable scrolling error sounds. After turning this on, I may never go back.
> Add option to disable scrollbar error sound

- library/strings.h
<cstdint> was likely included from another header on other platforms/versions
> Fix missing headers from gcc-13 build

- data/forms/recruitscreen.form
- game/ui/base/recruitscreen.cpp
- game/ui/base/transactionscreen.cpp
* recuritscreen now has correct subform
* recruitscreen and transactionscreen will now reference their forms correctly
* recruitscreen and transactionscreen will now hide and show forms correctly
> Added fixes for issue 1244

- appveyor-dev.yml
- appveyor.yml
- vcpkg.json
Latest master right now seems to cause install errors on 7zip
> Lock vcpkg to 2023.08.09

- data/forms/mainmenu.form
As per discussion, border gone and title changed.
> Change title and remove border from main menu

- data/forms/difficultymenu.form
Forgot to change the difficulty menu name and remove the border when the main menu was changed.
> Fix difficulty menu text and border

- data/forms/sheet_agent_profile.form
Addresses #1260
The agent stats tooltips are working again. Yay.
> Fix agent stats tooltips

- framework/data.cpp
- framework/framework.cpp
- framework/sound/sdlraw_backend.cpp
A couple of things could cause deadlocks or weird behavior if accessed from multiple threads - likely not really an issue as the situations are likely *extremely* uncommon
> Fix a couple of small threading issues

- forms/listbox.cpp
- game/state/city/city.cpp
- game/state/stateobject.h
- game/ui/base/vequipscreen.cpp
Fixes a few warnings/errors that happen to be hit by clang on MacOS.
> MacOS clang build fixes

- game/state/battle/battleunit.cpp
> Fix std::set iterator comparison in battlescape

- data/common_patch/gamestate/ufopaedia.xml
> Swapped cannon images

- game/ui/tileview/cityview.cpp
I was taking a look at PR https://github.com/OpenApoc/OpenApoc/pull/1402 and I decided to refactor updates a little bit for better readability. It shouldn't have any behavior change otherwise.
- Added `const` modifier at declarations whenever possible
- Broke `if` condition for ignoring vehicles into different boolean declarations
- Updated `redo` condition to use an early exit instead of having long list of code inside `if` structure
> Refactoring vehicle list at CityView::update() for better readability

- game/ui/general/agentsheet.cpp
> Add rank tooltip to agent profile

- game/state/city/vehiclemission.cpp
- game/ui/tileview/cityview.cpp
I was working on an issue but decided to push this refactoring as its own PR:
1. Simplified some `if` conditions
2. Removed redundant `if (true)` condition
> Refactoring vehiclemission and cityview

- game/ui/tileview/battletileview.cpp
Fixes #1449
Removes duplicate TU from agents head in debug mode.
> Fix duplicate TU above agents in debug mode

- data/forms/city/debugoverlay_city.form
- game/ui/tileview/cityview.cpp
- game/ui/tileview/cityview.h
Temporary fix for #1310 
Adds a debug option to fix the slow vehicle issue while I continue to work on it. Save included for testing (Retaliator 1 is stuck.)
[save_G4.Retaliator.Slo-Mo (1).zip](https://github.com/user-attachments/files/16536669/save_G4.Retaliator.Slo-Mo.1.zip)
> Add debug option to fix slow motion vehicles

- data/forms/city/debugoverlay_city.form
- game/ui/tileview/cityview.cpp
- game/ui/tileview/cityview.h
Remove the warp debug as it is now fixed, thanks @kgd192!
> Remove warp debug command

- game/state/gamestate.cpp
"No Vehicle object matching ID error" issue resolved.
Tested with these save files. This error was already resolved (I couldn’t reproduce it), but it didn’t work properly with old saves. It should work correctly now.
#931
#940
Facts (tested):
Old saves might contain an agent_id error.
When there are more than 12 passengers, the number is not displayed correctly.
My commit includes my previous fix because it wasn't merged into the main branch."
> FIX - [Cityscape] No Vehicle object matching ID "VEHICLE_19" #931#940

- data/forms/researchscreen.form
Resolves #1518
Good catch, thanks @XCOM-HUB
> Fix cutoff text in research screen

- framework/framework.cpp
- framework/options.cpp
- framework/options.h
- tools/launcher/launcherwindow.cpp
- tools/launcher/launcherwindow.h
- tools/launcher/launcherwindow.ui
I saw that OpenXcom had this and thought it would be a good addition.
> Add a mouse capture option
