OpenApoc/OpenApoc

game/apocresources/music.cpp
The second array is actually an array of ending offsets in the MUSIC file.
This removes music cutting mid-playing as well.
Note that, as of now, playing the same track again will not work - looks like the MusicTrack does not get rewinded.
=> Play music correctly.

framework/event.cpp, framework/event.h, framework/framework.cpp, framework/framework.h, game/state/research.cpp, game/state/research.h, game/state/ufopaedia.cpp, game/state/ufopaedia.h, game/ui/city/cityview.cpp, game/ui/ufopaedia/ufopaediacategoryview.cpp, game/ui/ufopaedia/ufopaediacategoryview.h
I don't really know if continually extending the already creaking Event system is the best idea... Should I push this now, or try to make Events cleaner, or fixup the ufopaedia_entry pointer from a ResearchTopic first?
Note: Currently the ResearchTopic::ufopaedia_entry field is not filled
out so it doesn't actually show the ufopaedia entry if you click
'yes'...
The ufoapedia_entry probably should be a list anyway, as some things
enable multiple entries (e.g. the toxigun research topic has entries for
the gun and ammo type A)
=> Add ID and data to UserEvent and use it for 'research complete'

framework/configfile.cpp, framework/configfile.h, framework/logger.cpp, portable.txt
Having a file called 'portable.txt' in the working directory when running an executable now causes the config file path to default to a local path, instead of a system-wide user path.
This should default-enable that mode for the build by adding a portable.txt in the root of the repository.
=> Add a "Portable" config mode

.travis.yml, tools/lint.sh, tools/travis-scripts/build_prepare_linux.sh
A recent travis update seems to have broken some packages, so I took
this opportunity to cleanup some things
Also adds a lint script (tools/lint.sh) that runs clang-format on
either:
The current git staging area (IE 'git diff --cached') with no arguments:
./tools/lint.sh
The provided revision range:
./tools/lint.sh master..branch
./tools/lint.sh SHA1..SHA2
No output is required to pass the lint builder. It must be run from the
root of the git repo, as it queries git for the modified files (and it
provides them relative to the root)
TODO:
- Re-add OSX
- Re-add sanitize builds?
- Debug builds?
- Static analysis builds? (clang-tidy?)
=> Resurrect travis build, add 'lint' pass

game/state/stateobject.h
Adding an explicit StateRef<> operator=(nullptr_t) allows gcc to figure
out:
StateRef<Obj> variable = nullptr;
msvc already allowed this by implicit conversion to constructing to an
sp<> first, but gcc rejected that as ambigious (As it should!) as it
can't tell if 'nullptr' was a GameState* or argument to sp<>
constructor.
=> GCC build fix

tests/test_serialize.cpp
It doesn't like (for example) re-ordering stuff, so is unreliable
=> Disable the roundtrip serialisation comparison

data/common_patch/gamestate/ufopaedia.xml, forms/listbox.cpp, forms/scrollbar.cpp, forms/scrollbar.h, framework/framework.cpp, game/state/city/building.cpp, game/state/city/building.h, game/state/city/city.cpp, game/state/city/city.h, game/state/city/vehicle.cpp, game/state/city/vehicle.h, game/state/city/vehiclemission.cpp, game/state/city/vehiclemission.h, game/state/city/vequipment.cpp, game/state/city/vequipment.h, game/state/gameevent.cpp, game/state/gameeventtypes.h, game/state/gamestate.cpp, game/state/gamestate.h, game/state/gamestate_serialize.xml, game/state/shared/organisation.cpp, game/state/tilemap/pathfinding.cpp, game/ui/base/transactionscreen.cpp, game/ui/base/vequipscreen.cpp, game/ui/general/ingameoptions.cpp, game/ui/skirmish/skirmish.cpp, game/ui/tileview/battleview.cpp, game/ui/tileview/cityview.cpp
- improved cityscape pathfinding is implemented and seems to work
properly in all cases
- an option to skip turbo calculations is implemented and will improve
the speed at which turbo speed goes on slower machines by making craft
move immediately all the way rather than tile by tile
- craft now spends fuel and crashes when out of fuel
- craft now requires engines
- when transferring via purchase screen involving hostile org (sell on
one base buy on another), goods are now transferred instead of purchased
(which is impossible as org is hostile to you)
- cargo seized or refunded now properly goes back to economy
- proper scrollbar redraw when max/min changes
=> improved p[athfinding and fixes

framework/render/gles30_v2/gleswrap.h
This should avoid any conflicts, as in issue #214
=> gleswrap: Use posix ssize_t on non-windows platforms

.gitignore, data/forms/sheet_agent_item.form, data/forms/sheet_vehicle_item.form, data/forms/transactionscreen.form, forms/control.cpp, forms/form.cpp, game/ui/base/transactionscreen.cpp, game/ui/base/transactionscreen.h
Allows to reuse forms like: agent item view, vehicle item view, agent view, etc.
<subform> properties can override the style properties defined in the source form
It seems that the subform body captures hover and click events, so it will shadow controls that are under it (possibly an undesired effect?)
=> Implement <subform> tag in forms

game/state/city/building.cpp, game/state/shared/agent.cpp
Fixes segfault caused by dereferencing a null pointer while updating agent healing/training when the agent is in a vehicle stationed in a base (Issue #248)
Fixes segfault caused by creating an invalid base defense event on alienMovement
=> fix several segfaults

data/forms/city/agentassignment.form, forms/CMakeLists.txt, forms/checkbox.cpp, forms/control.cpp, forms/control.h, forms/form.cpp, forms/forms.h, forms/forms.vcxproj, forms/forms.vcxproj.filters, forms/graphic.cpp, forms/graphicbutton.cpp, forms/label.cpp, forms/multilistbox.cpp, forms/multilistbox.h, forms/scrollbar.cpp, forms/textbutton.cpp, forms/textedit.cpp, forms/ticker.cpp, forms/tristatebox.cpp, game/OpenApoc.vcxproj.user, game/ui/base/transactionscreen.cpp, game/ui/city/alertscreen.cpp, game/ui/city/buildingscreen.cpp, game/ui/components/agentassignment.cpp, game/ui/components/agentassignment.h, game/ui/components/controlgenerator.cpp, game/ui/components/controlgenerator.h, game/ui/components/equipscreen.cpp, game/ui/components/locationscreen.cpp
UPDATED
Changes:
1. Added the MultilistBox class.
- extends the Control class.
- allow to multiselect items.
- allow to build hierarchical trees. Hierarchical "hover" and "select" can works too.
- uses strategy pattern for "hover" and "select" rendering.
- uses strategy pattern to make a decision about visible/invisible items.
- uses strategy pattern for behaviour during selection actions.
- can be use either with ScrollBar or without ScrollBar.
- works only for vertical orientation (yet).
2. Several changes in the Control class.
- added SelectionSize to the Control class. It's an area which can be hovered and selected. The old Size is the area where the Control rendered. In most cases they're the same but not for the MultilistBox.
- changed meaning of the Control::preRender(). From now …
=> refactoring Agentassignment

game/state/city/city.cpp, game/state/city/city.h, game/state/gamestate.cpp, game/state/gamestate.h, tools/extractors/extract_vehicles.cpp
Now all the initial equipment for vehicles must be defined explicitly. Don't assume that the initial equipment is the same as the vehicle's default.
See issue #254
=> set correct initial equipment for vehicles

game/ui/tileview/citytileview.cpp
fixed issue #242 "Night time affects the tactical view of the city. In the original there is always a day"
=> fixed palette of the city view strategy mode

appveyor-dev.yml
This removes some stuff from the appveyor -dev builds - this is only used on non-master branches, so somewhat less useful to the the average joe.
Disable win32 (only 64-bit now), and use 7z instead of .zip to pack better, remove all .exes other than OpenApoc.exe from package
=> Trim down appveyor-dev builds

dependencies/libsmacker.vcxproj, dependencies/lodepng.vcxproj, dependencies/miniz.vcxproj, dependencies/miniz.vcxproj.filters, dependencies/physfs.vcxproj, forms/forms.vcxproj, framework/font.cpp, framework/framework.vcxproj, game/OpenApoc.vcxproj, game/state/battle/battleunit.h, game/state/gamestate.vcxproj, game/ui/gameui.vcxproj, game/ui/gameui.vcxproj.filters, library/library.vcxproj, library/library_pch.h, library/strings.cpp, library/strings.h, tests/CMakeLists.txt, tests/test_images.vcxproj, tests/test_rng.vcxproj, tests/test_serialize.vcxproj, tests/test_unicode.cpp, tools/extractor.vcxproj, tools/gamestate_serialize_gen/gamestate_serialize_gen.vcxproj, tools/imagedump/imagedump.vcxproj
The previous insert/remove used /bytes/ for the offset, not codepoints,
causing weirdness as users (e.g. TextEdit) would end up
removing/inserting bytes within a utf8 codepoint - which would cause
invalid codings (which were probably ignored), showing as multiple
keypresses being required to delete a non-ascii character
Now, the iterator stores the offset in bytes, but as the utf8 conversion
routines let us know how many bytes each codepoint contains, we can use
that to skip/remove the correct number of bytes accordingly.
This also removes some users of boost::locale's utf conversion, wipes some headers, simplifies toUpper/toLower, and adds a test for some of the UString functions
=> UString insert()/remove() fix

framework/configfile.cpp
Some std::filesystem implementations (e.g. GCC7) don't like trying to
create a directory for an empty path, which was happening for portable
mode. This stopped the config file being written.
=> Fix config file write in portable mode

framework/serialization/serialize.cpp, framework/serialization/serialize.h, game/state/gamestate.h, game/state/gamestate_serialize.cpp, game/state/gamestate_serialize.h, game/state/savemanager.cpp, game/state/savemanager.h, tools/gamestate_serialize_gen/main.cpp
The lifetimes of these objects is known, so there's no need for shared
ownership.
Might make things a little faster if we're doing doing lots of atomic
refcounting...
=> Remove some (unnecessary) sp<> wrappers in the serializer

game/ui/city/alertscreen.cpp, game/ui/city/buildingscreen.cpp, game/ui/components/agentassignment.cpp, game/ui/components/locationscreen.cpp
fixed the first issue from #291 
> First issue i had is a crash when i tried to outfit a vehicle.
> You click on the icon with the vehicle and the + sign at the UI menu at the bottom and from that screen click on the top right vehicle with the missile and it crashes.
=> fixed currentAgent and currentVehicle selection

data/forms/city/bribe.form, game/state/shared/organisation.cpp, game/state/shared/organisation.h, game/ui/CMakeLists.txt, game/ui/city/bribescreen.cpp, game/ui/city/bribescreen.h, game/ui/gameui.vcxproj, game/ui/gameui.vcxproj.filters, game/ui/tileview/cityview.cpp
- Implemented the BribeScreen.
- Since the relation is float instead of int, changed the calculation of thresholds.
`	float x = this->getRelationTo(other);`
`	if (x < -50)	{ return Relation::Hostile; }`
`	else if (x < -25)	{ return Relation::Unfriendly; }`
`	else if (x < 25)	{ return Relation::Neutral; }`
`	else if (x < 75)	{ return Relation::Friendly; }`
`	else	{ return Relation::Allied; }`
It is not exactly like vanilla, but very close. This approach allow to simplify calculations and reduce the number of bugs. Another approach is use the int relation like vanilla.
The screen:
=> implemented the BribeScreen

game/state/city/vehicle.cpp
fixed issue #260 "No vehicle matching ID "VEHICLE_794" CTD"
=> fixed vehicle.die()

game/state/gamestate.cpp
fixed issue described in #260 
When quit game the destructor of Lab calls to agents from list, but agents already destroyed.
Simplest way is to clear the Lab's agents list in the GameState destructor.
=> fixed destructor of GameState

game/state/city/vehiclemission.cpp, game/state/city/vehiclemission.h
partially fixed the issue #339 "Destroyed buildings often trap vehicles in their basement causing performance issues and eventual CTD."
- if really impossible to leave a building, then next attempt will be after 30 min.
- the self-destruct timer for UFO was hardcoded as described by @FilmBoy84 #339
- the self-destruct timer for vehicles decreased to 1 hour.
=> fixed mission timers

game/state/city/vequipment.cpp, game/state/city/vequipment.h, game/state/gameevent.cpp, game/state/gamestate.cpp, game/state/rules/city/vammotype.cpp, game/ui/base/buyandsellscreen.cpp
Fixed typo in buy and sell screen.
Related to:
No aequipement type matching ID "VEQUIPMENTTYPE_BOLTER_4000_LASER_GUN"
#353
Selling vehicle equipment/ammo resulted in selling non existing agent
equipment and ammo.
=> Fix bug when selling vehicle equipment or ammo

README.md
This will modify the README.md on how and what to install on Mageia 6 (and above) in order to sucessfully compile OpenApoc on Mageia.
This might also work on «OpenMandriva» and «Rosa Linux»
=> Add build instructions for Mageia 6

CMakeLists.txt, tools/extractors/CMakeLists.txt
If you set the cmake var EXTRACT_DATA to off (default on), it no longer causes
the data extractor to be run as part of the default build. This means CD_PATH
would no longer need to point to a valid file, for example.
The extraction step can still be run with the 'extract-data' target - make sure
this is run before trying to run the game or any tests!
=> Make the data extraction an optional step in cmake

game/state/city/base.cpp
This would have screwed up all base/building links, possibly breaking all kinds
of stuff
=> Fix equality bug when rerouting cargo from newly destroyed base

game/ui/base/buyandsellscreen.cpp
When selling vehicles the switch was not exited and caused bugs related
to agent equipment.
=> Fix to #389 & #260

framework/serialization/providers/providerwithchecksum.cpp, tools/gamestate_serialize_gen/main.cpp
boost/uuid/sha1.hpp has been deprecated and moved to boost/uuid/detail/sha1.hpp
=> fix compilation for boost >= 1.66

library/vec.h
This should hopefully fix issue #414 - it seemed that the previous
update was unintentionally reverted - but we'll just roll up to the
latest tag
=> Update to GLM 0.9.9.2 release

forms/transactioncontrol.cpp, forms/transactioncontrol.h, game/ui/base/aliencontainmentscreen.cpp, game/ui/base/buyandsellscreen.cpp, game/ui/base/transactionscreen.cpp, game/ui/base/transactionscreen.h, game/ui/base/transferscreen.cpp
Made the algorithm to populate the vehicle equipment screen simpler (should fix #362)
Transaction controls are now linked through a shared list of weak pointers which should be more efficient. The previous solution was to keep a list of shared ptrs to every linked node per node, thus creating a mesh of O(n^2) complexity. Keeping a shared list should provide O(n) complexity. Also updates nodes on being linked (fixes #394)
=> refactor algorithm to populate vehicle equipment controls

game/state/rules/city/vequipmenttype.cpp, game/state/rules/city/vequipmenttype.h, game/ui/general/vehiclesheet.cpp, game/ui/ufopaedia/ufopaediacategoryview.cpp
As discussed in the discord: the range values in apoc's data file seem to be in half-metres. This fix should scale them accordingly while still displaying the value in tiles, as intended (related issue #361)
=> scale weapon range correctly in vehicle equipment sheet

game/state/city/vehicle.cpp
Vehicles controlled by non-xcom organisations would not attack targets if they were non-aggressive (even if they were hostile towards them)
=> fix acquiring enemy for non player vehicles

framework/framework.cpp, game/state/gamestate.cpp, game/ui/general/ingameoptions.cpp
The Wolfhound APC can now be made all-terrain, just like the Griffon Tank
=> Make Wolfhound APC All-Terrain Capable via (M) Option

game/ui/tileview/battletileview.cpp, game/ui/tileview/battletileview.h, game/ui/tileview/battleview.cpp
Display the TU cost to fire when hovering over a hostile unit in the battlescape in turn-based mode, like in vanilla apocalypse
=> fix firing TU cost display in TB mode

game/state/shared/organisation.cpp
This should prevent hirable agents from spawning from buildings with bases. See #448
=> updateHirableAgents only spawns civilian hirees from non-bases

framework/configfile.cpp, framework/configfile.h
A bug where option values with spaces were marked as invalid was accidentally introduced in #443. This should fix it
=> Validate UStrings for boost::program_options

forms/transactioncontrol.cpp, game/ui/base/buyandsellscreen.cpp, game/ui/base/transactionscreen.cpp
This fixes a bug introduced in #425 which was causing #440 (unlinked transactioncontrols wouldn't update the resource deltas)
Also refactors the algorithm for calculating deltas from transaction controls: previous implementation would store a set of known linked controls to avoid duplicating calculations.
=> TransactionControl fixes

CMakeLists.txt, game/state/savemanager.cpp
Adds the version strings to the save manifest. Hopefully useful to see exact versions when debugging with uploaded saves.
Currently not read by any openapoc code.
=> Store version string in saves

game/ui/gameui.vcxproj, library/library.vcxproj
This was causing build failures, as it was previously only being built as part
of the gameui, but now other modules (e.g. the savemanager of game/state)
started using the version strings.
Moved to the 'library' project, as everything already depends on that.
=> MSVC build fix: Move version.h generation to library project

game/state/city/vehicle.cpp, game/state/city/vehicle.h
When calling `Vehicle::setMission`, it's possible for some missions to reach the front in the vehicle's mission list without being properly started. Here's an example:
Before clearMissions:
```
front          back
v              v
Snooze, TakeOff, X
```
After clearMissions:
```
TakeOff
```
After addMission:
```
TakeOff, X
```
Here, the TakeOff mission was never started although it is at the front of the list. X can be another mission like AttackVehicle, GotoLocation, GotoBuilding, etc.
This may be the cause of #456, although it won't fix the already broken saves.
=> Fix vehicles becoming stuck in buildings when clearing missions

library/strings.cpp, library/strings.h
=> fix UString::substr to use offsets in codepoints (instead of bytes)

forms/textedit.cpp
Preventing the widget from restarting the SDL text editing mode allows sequences such as `´`, `e` to properly transform into an input `é`, for example
=> Dont restart text input mode while using the same TextEdit

game/state/tilemap/tile.cpp
I've updated the work by @kaja47 to fix the grav-lift item problem
Co-Authored-By: K. <kaja47@users.noreply.github.com>
Rebased version of PR #480
=> Fix for Grav-Lift item falling through floor

data/common_patch/gamestate/facility_types.xml
This makes the repair bay restore 12HP per hour for vehicles being repaired (currently it's just 1HP an hour!!!)
It is not a complete fix as we need to make future considerations for repair bay capacities and vehicle types in the future to comply with OG
Additionally, in Beta Apoc, repair rate was variable with difficulty level!
=> [Quick-Fix] for HP repair value for vehicles in repair bay

game/state/gamestate_serialize.xml
Should fix the error regarding unknown vehicle mission type when loading a savegame at the start of a UFO incursion (reported by @BeornTB on discord)
=> serialize VehicleMission::MissionType::ArriveFromDimensionGate

data/forms/city/tab1.form, data/forms/ingameoptions.form, forms/control.cpp, forms/control.h, forms/forms_enums.h, framework/framework.cpp, framework/framework.h, game/ui/general/ingameoptions.cpp, library/strings.cpp, library/strings.h
Adds configurable tooltips (font, background color, border color)
Note that only the tooltip for the 'Bases' button in the cityscape was implemented. The rest of the tooltips should be added in the appropiate form files
=> Add tooltips

data/forms/ingameoptions.form, forms/listbox.cpp, forms/scrollbar.cpp, game/ui/general/ingameoptions.cpp
* Allow mouse-move interactions with captured scrollbar even outside of its' bounds (easier dragging, especially near the left end of the scrollbar)
* Adjust the scroll limits according to the parent listbox's contents (easier scrolling in a listbox with many items)
=> List control tweaks

game/ui/tileview/cityview.cpp
Fixes a bug introduced in #448 where I tried to use a POSIX argument position in a format specifier and I ended up using a width specifier instead. Anyways, argument positions are not supported in tinyformat atm so it's better to remove this.
=> Fix unused width specifier on investigation prompt

data/forms/city/tab1.form, forms/control.cpp, forms/control.h
Some fixes for bugs and code issues regarding tooltips that I noticed after 42b30ef was merged:
* Default tooltip settings were moved to `forms/control.cpp` (there were mismatching defaults declared in `forms/control.h` and `forms/control.cpp`)
* Borders specified in XML files will replace the default borders (they should no longer stack on top of them)
* Removed tooltip padding option (use a fully transparent border instead)
* Border thickness used to be ignored
=> Tooltip fixes

data/forms/city/city.form, game/ui/tileview/cityview.cpp, game/ui/tileview/cityview.h
* Link subforms in XML instead of hardcoding the names of the forms for the tabs
* Sets correct order for event handling (active tab is processed after the base form). This should make tooltips work in the base form
=> refactor CityView to use subforms

game/state/battle/battle.cpp, game/state/battle/battlehazard.cpp, game/state/battle/battlehazard.h
=> fix hazard removal while iterating

data/forms/ingameoptions.form, game/ui/base/recruitscreen.cpp, game/ui/base/researchscreen.cpp, game/ui/general/ingameoptions.cpp
The following text strings wouldn't pick up translations:
* `Exit Battle`
* `Skirmish Mode`
* `OpenApoc Features`
* `Message Toggles`
=> Add missing text translations in in-game options menu

game/ui/general/difficultymenu.cpp
The Game.Mods option contains a ":" separated list of mods to be loaded from
the data directory
e.g. if I have a new mod, "fancy_mod" in data/, then running OpenApoc with the
option:
--Game.Mods="fancy_mod"
should load it.
And multiple mods like:
--Game.Mods="fancy_mod:second_mod:third_mod"
=> Add a cmdline option for loading mods

forms/control.cpp
This could cause heap overflows and crashes.
=> Check an Event is a form event before trying to read the form union

game/ui/tileview/tileview.cpp, game/ui/tileview/tileview.h
Some weren't set in the constructor, which might cause the tileView to start
scrolling until the first mouse move event
=> Fix some unset variables in the TileView

forms/control.cpp
If unset, use "smallset" (settable with Forms.TooltipFont option).
Fixes crashes due to null unset tooltip fonts when trying to show the tooltip
=> Set a default tooltip font

framework/framework.cpp
This should ensure that any possibly cached images are destroyed first,
as their destructors can call back into the Renderer to destroy any
private data.
Doing this should avoid a crash at exit due to use-after-free of the
renderer.
=> Destroy the Data implemention before the renderer

framework/framework.cpp
On non-android platforms, touch events are now default ignored. Set the
Framework.EnableTouchEvents option to override.
=> Add an option to ignore touch events

framework/framework.cpp
Use std::shuffle with a URBG instead
=> Fix build on c++17 due to removed std::random_shuffle

game/state/battle/battleunit.cpp, game/state/battle/battleunit.h
These dangling references can cause crashes (e.g. in the brainsucker's AI
"find target" code)
=> Remove units that retreat from the Battle's visible unit lists

game/state/battle/battlemappart.cpp, game/ui/tileview/battletileview.cpp
The double negative (x=center.x - (-0.5)) looks wrong for the left wall, as the left wall should be (-0.5) from the center? As the tilemap origin 0,0 is at the top-left?
=> Fix BattleMapPart death explosion doodad position

game/ui/general/agentsheet.cpp
Minor interface fix of non-critical visual problem.
Current interface have only only 88 pixels for stats bar width, but its set to 100 in code.
So stats bars with > 88 of width are out of boundaries.
So I simple changed ImageSize.x in AgentSheet::StatsBar to 88 from 100.
=> Fix UI agent stats bar boundaries in Agent Equipment Sheet

game/ui/tileview/battleview.cpp
Without this, large accuracy values may go over the end of the accuracy bar
image, hitting a LogAssert
=> Clamp the accuracy indicator to the image width

game/state/gamestate_serialize.xml
This was missing from the serialization generation source, so any saves that
happened to contain missions of this type would fail
=> Add VehicleMission::MissionType::RestartNextMission enum serialization

game/ui/general/aequipscreen.cpp
Previously, they were re-processed every time there was a key event on each of
the numbers, so each of {up, down, press}, causing it to be processed
multiple times needlessly
=> Cleanup agent equipment screen code

game/state/city/research.cpp
Previously only a single unit was created, which is intepreted as a single
round, so would take multiple manufactured units to be considered a complete
clip
=> Manufacture ammunition a whole clip at a time

CMakeLists.txt, CODE_STYLE.md, appveyor-dev.yml, appveyor.yml
Puts a hard requirement on newer toolchains, but allows us to guarantee use of all c++17 features and avoid nasty compat wrappers, so IMHO worth it
=> Enable c++17 use

game/state/battle/battle.h, game/state/city/city.h, game/state/city/scenery.cpp, game/state/city/scenery.h, game/state/city/vehicle.cpp, game/state/city/vehicle.h, game/state/rules/aequipmenttype.cpp, game/state/rules/aequipmenttype.h, game/state/rules/agenttype.h, game/state/rules/battle/battlemap.cpp, game/state/rules/battle/battlemap.h, game/state/rules/battle/battlemapsector.cpp, game/state/rules/battle/battlemapsector.h, game/state/rules/city/baselayout.h, game/state/rules/city/scenerytiletype.h, game/state/rules/city/vehicletype.h, game/state/rules/city/vequipmenttype.cpp, game/state/rules/city/vequipmenttype.h, game/state/shared/agent.h
Also replaces some 'trivial' constructors with default constructor and member initialization - it's a lot more obvious having the initializer at declaration to see if you've missed something.
=> Fix a number of unset variables in default-constructed game objects

library/strings_format.h
We assume anything that defines __GNUC__ also copes with GCC #pragmas
=> Disable -Wimplicit-fallthrough when including tinyformat

framework/CMakeLists.txt
Not sure why this affected me and not the CI - maybe different paths?
But as the SDL headers are used in public framework headers, we need to use PUBLIC here so things that then link to the framework also inherit the SDL include paths etc.
=> Fix MSVC build failure: missing SDL_keycode.h

game/state/shared/agent.cpp
Non-xcom agents may have a 'home building' without a base, so check
the existance of a base before deref-ing to see how many medical bays
there are.
=> Fix crash when healing agents not in a building with base

game/ui/general/savemenu.cpp
Even if we're saving, we hide the TextEdit until a save slot has been selected,
as until then the names are displayed by a Label and the TextEdit not intended
to be active.
=> Always hide SaveMenu TextEdit control at screen open

game/state/city/vehicle.cpp, game/state/city/vehicle.h, game/state/gamestate.cpp, game/state/gamestate_serialize.xml
Vehicles currently in a dimension gate are currently assigned a tileObject in
GameState::initGame(), despite them not having valid position coords, so appear
on the map at a nonsense location (0,0,0) and hit a LogError() in
Vehicle::leaveDimensionGate() as it doesn't expect an existing tileObject.
So instead store a flag for if a Vehicle is between dimensions - and don't
create TileObjects for Vehicles with that flag set at game load time.
Note: This doesn't fix existing saves where there are vehicles currently in the
gates, as the flag won't be set correctly. New games, or games loaded from a
state where there aren't any Vehicles that happen to be in the gates at that
moment, should be fine going forward.
=> Don't create tileObject of vehicles between dimensions at game load

tools/extractors/extract_vehicles.cpp
This is what was causing the Alien Assault ship to be unhittable/unselectable
Note this data is stored in the saved game state, so new games will be required
=> Fix LOFtemps for vehicles with exactly 16-high LOFTemp stacks

framework/CMakeLists.txt, framework/framework.cpp, framework/logger.cpp, framework/logger.h, framework/logger_file.cpp, framework/logger_file.h, framework/logger_sdldialog.cpp, framework/logger_sdldialog.h
Use callbacks for each log output option (file, SDL dialog), with a default of "anything warning and above to stderr"
This is a prerequisite for things to wrap the Framework where you might want to get logs out - like an editor or something ;)
=> Allow the Logger to be hooked

framework/serialization/providers/providerwithchecksum.cpp
They aren't really that useful, I added them to detect damaged or partially
updated gamestate trees - but haven't seen that in so long the extra annoyance
to modmakers modifying stuff doesn't seem worth it
=> Disable gamestate CRC checksums by default

library/colour.cpp
The logger is part of the framework, which isn't linked into the library
=> Remove logger use from Library/colour.cpp

framework/framework.cpp
Otherwise it writes to a "user" location, which may not be intended
=> Write log file to ./log.txt in portable mode

forms/control.cpp, framework/CMakeLists.txt, framework/configfile.cpp, framework/configfile.h, framework/data.cpp, framework/framework.cpp, framework/logger_file.cpp, framework/logger_sdldialog.cpp, framework/options.cpp, framework/options.h, framework/serialization/providers/providerwithchecksum.cpp, framework/trace.cpp, game/state/savemanager.cpp, game/ui/boot.cpp, game/ui/general/difficultymenu.cpp, game/ui/general/loadingscreen.cpp
Without this some options may be DCE'd by the linker, so we lose the definitions, so are removed from the config file by the tool that doesn't recognize them.
=> Ensure all option definitions are linked to all tools

game/state/battle/battleunitmission.cpp
I think this may be a possible cause of a deadlock - if a unit can't route any
closer to it's intended destination, it'll loop in Restart->Goto->Restart
forever.
Adding a 1 tick snooze should allow the game to progress, and possibly allow the
blockage to clear itself if it's temporary (e.g. another unit)
=> Snooze for a tick when restarting a GoTo mission that's blocked

game/state/battle/battleunitmission.cpp
Deleting this current mission could cause crashes due to use-after-free errors
on any subsequent mission data access
=> Don't remove the current TeleportMission in TeleportMission's start()

game/ui/base/transferscreen.cpp
This was causing a crash as agent->lab_assigned will be nullptr on
agents not assigned to a lab.
=> Don't try to remove unassigned scientists from lab when transferring

.travis.yml
We need newer boost for filesystem::relative().
This also requires using some manual apt- commands, as it seems the apt repos we
want aren't enabled for the travis apt addon on bionic
=> Update travis to ubuntu 18.04

game/state/gamestate.cpp, game/state/rules/aequipmenttype.h, game/ui/general/aequipmentsheet.cpp, game/ui/ufopaedia/ufopaediacategoryview.cpp
It doesn't make sense to have duplicate ammo types, so making it a set collapses
that down
=> Make AEquipmentType::ammo_types a set

.gitignore, framework/CMakeLists.txt, framework/framework.cpp, framework/framework.h, framework/fs.h, framework/modinfo.cpp, framework/modinfo.h, framework/options.cpp, framework/options.h, framework/physfs_fs.cpp, game/state/gamestate.cpp, game/state/gamestate.h, game/ui/boot.cpp, game/ui/general/difficultymenu.cpp, tests/CMakeLists.txt, tools/extractors/CMakeLists.txt, tools/extractors/main.cpp, tools/launcher/launcherwindow.cpp, tools/launcher/launcherwindow.h, tools/launcher/launcherwindow.ui
Now mods are stored in the "Game.ModPath" folder (defaults to ./data/mods) - each mod has it's own subdirectory with a "modinfo.xml", which contains - for example:
```
<?xml version="1.0"?>
<openapoc_modinfo>
<name>OpenApoc cool mod</name>
<author>OpenApoc team</author>
<version>0.1</version>
<description>A super cool mod for OpenApoc</description>
<link>http://www.openapoc.org</link>
<id>org.openapoc.mods.JonnyH.super_cool_mod</id>
<datapath>new_data_directory</datapath>
<statepath>gamestate_patch</statepath>
<minversion>0.0</minversion>
<requires>
<entry>org.openapoc.base</entry>
</requires>
<conflicts>
<entry>org.openapoc.mods.JonnyH.conflicting_mod</entry>
</conflicts>
</openapoc_modinfo>
```
which mean:
All but ```<name>``` and ```<id>``` are technically optional, but it's worth …
=> Rework mod support, add packages and manager to launcher

game/state/gamestate_serialize.cpp, game/state/rules/battle/battleunitimagepack.cpp, tools/extractors/main.cpp
As the serialize code doesn't use physfs' open by default, it wasn't searching
the correct data directories for mods.
=> Fixup mod battleunit imagepack search directories

framework/logger_file.cpp
May help issues on windows where the log is near useless after a crash?
=> Flush stream in file_logger on warning and above

framework/fs.h, framework/physfs_fs.cpp
It doesn't affect FileSystem state, so can be const.
Also FileSystem::getCorrectCaseFilename() isn't implemented or used anywhere, so
remove that from the header.
=> Make FileSystem::open() const

game/state/battle/battleunit.cpp, game/state/tilemap/tilemap.h
This was causing tile out-of-bounds errors when a giveWayRequest would try to
move an agent off the edge of the map.
=> Check if a tile is out of bounds in BattleUnit::updateGiveWay()

game/ui/base/buyandsellscreen.cpp
Clamp against the current round inventory count, as otherwise selling your last
partially filled clip will underflow the 'unsigned' inventory cound and you get
a silly value.
Note that as the market only tracks whole clips, this cause selling and rebuying
a partially filled clip to refill it for free, but that seems less worse than
giving the player ~4 billion rounds.
=> Don't underflow inventory selling partially-filled ammo clips

.clang-tidy, .travis.yml, game/state/CMakeLists.txt, tools/lint-tidy.sh
This runs clang-tidy with a subset of possibly-useful checks on modified files in the travis CI, hopefully pointing out possible issues. Only build failures would fail the pass, however, so it's more for info than anything else.
=> Add a clang-tidy script, and run it in the travis 'lint' pass

game/state/gamestate.cpp
A quick fix for the stormdog ammo being empty on starting a new game
=> Fix the Stormdog not having full ammo loaded on game start

appveyor-dev.yml, appveyor.yml
We don't need a specific point release, and I think this is breaking appveyor as they scrub older point releases
=> Don't specify appveyor qt5 point release version

framework/framework.cpp, framework/options.cpp, framework/options.h
This sleep()s if we're going faster than the expected update rate,
hopefully avoiding any possible issues due to different vsync limits
causing significantly different in-game speeds - as it's set to
progress 1 tick every frame.
Note that if you are 60fps vsync limited (or lower) there's a good
chance the update loop will 'fall behind' due to natural jitter and
precision differences, it'll LogWarning() if that happens, but it
shouldn't cause any real issues, so long as the difference is small.
If you somehow ended up with some weird setup with a significantly lower
than 60fps vsync, however, it will run slower.
=> Lock the framework update loop to a set FPS (default 60)

game/state/gamestate_serialize.h
Basic type (e.g. 'float' or 'int') aren't set to a defined value if just
declared as "int x;". "int x{};" however should guarantee a defined
(zero) value.
This could have caused corrupted saves if the 'random' undefined
default happened to match the intended value when saving, but not the
expected default when loading.
=> Always explicitly construct default 'reference' objects in serializeOut

appveyor-dev.yml, appveyor.yml
Should cause any caches to be deleted.
Then we can re-add them.
Hoping to solve the "error 500" from artifact storage on appveyor - I
assumed it was storage limits, but having removed a number of builds and
still getting errors not so sure.
=> remove cache entries from appveyor.yml

appveyor-dev.yml, appveyor.yml
- Update the build toolchain to msvc2019
- Update vcpkg to 2019.12
- Don't hardcode git checkout path, instead use %APPVEYOR_BUILD_FOLDER%
- Re-enable vcpkg cache
=> Appveyor: A number of updates

game/state/city/base.cpp, game/state/gamestate.h, game/state/gamestate_serialize.xml, game/ui/city/basebuyscreen.cpp, game/ui/tileview/cityview.cpp, game/ui/tileview/cityview.h
Refreshes base icons after losing a base.
Keeps track of the base number uses it to continually name new bases.
Merged commits for this one.
=> Fix to #799

CMakeLists.txt, framework/framework.cpp, tools/extractors/CMakeLists.txt
Very much a WIP:
- Only the OpenApoc executable is packaged - we probably want /at least/
the launcher in there too
- The post-build copy cmake command for the data/ directory into the
resources feels like a hack - same with the fixed location .app bundle
name where it's copying them to? Probably some cmake property we can
query?
- It seems the working directory of app bundles is always "/"? Which
breaks all the loading "local" data, so we chdir() based on the SDL
"base directory", which seems to point to the Resources dir in the
bundle?
- Keying the above off the working directory being "/" is a hack - e.g.
run from the terminal it may be unlikely and maybe a bad idea, but
possible that "/" was the intended working directory - at which point I
don't really know that the SDL "base dir" …
=> WIP MacOS App bundle creation

data/common_patch/gamestate/agent_types.xml, game/state/battle/battleunit.cpp, game/state/rules/agenttype.h
The brainsucker pods are triggering correctly but Androids should not trigger them.
#762
I think this is how it worked in the original. In the original the aliens do not even target the androids if they are carrying the brainsucker launcher.
=> Androids do not trigger brainsucker pods

game/state/battle/battle.cpp
=> Deactivate medikits and motion scanners at the end of battle.

LICENSE, README.md
MIT is useful if you actually think people will find a use for your code that doesn't directly compete (e.g. libraries etc), but most of OpenApoc's code is only really useful to make an Apoc clone - so may as well enforce code feedback as they only other real use is ClosedApoc
Note that historical versions released under the MIT license remain that way, as you can't revert a license like that :)
=> Relicense to GPLv3

game/state/battle/battleunitmission.cpp
=> Cancel movement if the closest path ends at the current position.

framework/serialization/serialize.cpp, framework/serialization/serialize.h, game/state/gamestate_serialize.h
This adds a way of removing items from lists/maps/vectors/sets in the GameState.
Copied from #784 (which this should help solve):
Adding 'commands' to lists (e.g. 'append'/'delete') in the xml format has been on the todo list for a while - and is necessary for issues like this.
I'm generally leaning towards an attribute instead of a subnode, but I think the bikeshed should be painted mauve.
e.g. a 'op' attribute, only valid on lists/vectors/maps and map keys (though the last can be overridden, it's not currently possible to /remove/ them)
- For lists and vectors (as they're treated the same) the 'op' attribute can gave one of two values, 'append' and 'delete' - 'append' being the default. To replace a list, use 'delete' and then follow it with the new entries as normal.
e.g.
```
<my_list …
```
=> WIP: add op="delete" attribute to serialization xml

data/common_patch/gamestate.xml, data/common_patch/gamestate/vehicle_types.xml, tools/extractors/common/vehicle.h, tools/extractors/extract_vehicles.cpp
All dimension-capable vehicles have a non-zero value here, so use that
to extract if they're dimension-travel capable
Outside of 'nonzero' I'm not sure what the values mean - maybe speed, as
the larger/slower craft seem to have 1, while the fastest 8?
For reference:
VEHICLETYPE_ALIEN_PROBE: 8
VEHICLETYPE_ALIEN_SCOUT: 2
VEHICLETYPE_ALIEN_TRANSPORTER: 2
VEHICLETYPE_ALIEN_FAST_ATTACK_SHIP: 5
VEHICLETYPE_ALIEN_DESTROYER: 3
VEHICLETYPE_ALIEN_ASSAULT_SHIP: 2
VEHICLETYPE_ALIEN_BOMBER: 3
VEHICLETYPE_ALIEN_ESCORT: 4
VEHICLETYPE_ALIEN_BATTLESHIP: 1
VEHICLETYPE_ALIEN_MOTHERSHIP: 1
VEHICLETYPE_POLICE_HOVERCAR: 0
VEHICLETYPE_AIRTAXI: 0
VEHICLETYPE_RESCUE_TRANSPORT: 0
VEHICLETYPE_CONSTRUCTION_VEHICLE: 0
VEHICLETYPE_AIRTRANS: 0
VEHICLETYPE_SPACE_LINER: 0
VEHICLETYPE_PHOENIX_HOVERCAR: 0 …
=> Extractor: Vehicles seem to have a 'dimension travel' flag

game/ui/general/aequipscreen.cpp
This makes it way less frustrating to equip solders - less guessing
which x/y position that slot happened to be defined at (which is
visually off for the armor, certainly).
It current tries in the order (+x, -x, +y, -x, +x+y, +x-y, -x+y, -y-y),
and seems to do the 'right' thing most of the time.
=> Check adjacent slots if dragging equipment to an invalid slot

framework/options.cpp, framework/options.h, game/state/gamestate_serialize.xml, game/state/shared/aequipment.cpp, game/state/shared/aequipment.h, game/ui/general/ingameoptions.cpp
This stops annoying stuff like autocannons switching to HE ammo and
shooting your feet, despite still having a spare AP reload available
=> Make ammo autoreload prefer the same type as previously loaded

game/ui/base/researchselect.cpp
Fixes `researchselection` when already-in-progress list item unable to select after changing selection.
Found this bug and fix it while trying to fix #786
=> [interface] Fix selecting already-in-progress list item after change selection

game/ui/tileview/battleview.cpp
Fixes a battlescape debug CTD when stunning a unit with [S] is preceded by removing some other unit(s) with [K].
=> Fix debug unit stunning in presence of retreated units.

framework/logger.cpp, library/backtrace.cpp, library/backtrace.h
Add it to failed asserts, as otherwise it'll abort() even in a debugger,
which is less than ideal
=> Add a debug_trap that should break to an attached debugger

game/state/city/vehiclemission.cpp, game/state/city/vehiclemission.h, game/state/shared/organisation.cpp
Adjusts decision making for rescue-capable crafts to not consider unreachable crashes as viable targets.
This prevents Rescue Transports from becoming stuck in the "GotoLocation - RestartLastMission" loop trying to recover a crashed craft obstructed by a scenery, while ignoring other crashes.
=> Don't attempt to rescue unreachable craft.

data/forms/recruitscreen.form, data/forms/transactionscreen.form
Transaction screen before PR:
Transaction screen in vanila:
Recruit screen before PR:
Recruit screen in vanila:
=> Align filled and unfilled parts of progress bars on Recruit and Transaction screens.

game/ui/tileview/citytileview.cpp
After a UFO battle ends XCOM vehicle gets assigned an `Offer Service` mission without a target building, resulting in a CTD if player switches to the city tile view.
https://github.com/OpenApoc/OpenApoc/blob/e65b5fe4a1d997ed1d8bcbd3c2e313ae4307ab74/game/state/battle/battle.cpp#L3362
=> Fix a CTD on opening the tile view while a vehicle returns from UFO recovery.

game/state/battle/battle.cpp
Resolves an issue with "resurrecting" vehicles when loading a save game made right after a battle (e.g. UFO recovery).
The issue manifests if player saves the game right after a UFO recovery battle concludes and before unpausing the cityscape, and loads this save file -- the recovered UFO gets "resurrected".
Here's a repro save game -- unpause and wait for the battle to end, save the game in cityscape and load the saev:
[save_issue-recovered-ufo.zip](https://github.com/OpenApoc/OpenApoc/files/4656524/save_issue-recovered-ufo.zip)
=> Remove all dead vehicles immediately after a battle.

game/state/battle/battle.cpp, game/state/battle/battleunit.cpp
Removes popper's body from the battlescape if it dies violently (i.e. self-destructing), and prevents X-COM from recovering it.
Resolves #745.
=> Vaporize popper's body on "self-destruct".

game/state/city/vehiclemission.cpp
Falling UFOs no longer survive the crash in Alien Dimension.
Resolves #682.
=> Destroy falling UFOs on touchdown in Alien Dimension.

game/state/gamestate.cpp
Resolves a CTD on `CityView::render` when the list of selected vehicles contains a non-present entry.
Although the issue was uncovered as a result of #878, it manifests under different circumstances as well; here's a repro:
1. Fly to Alien Dimension.
2. Order XCOM units to return to Human Dimension.
3. Select any UFO and leave it selected till cityscape changes to Human Dimension.
4. Wait for the selected UFO to invade Human Dimension.
5. Destroy it.
6. Save the game.
7. Reload the game.
8. Fly to Alien Dimension.
Related to https://github.com/OpenApoc/OpenApoc/issues/788#issuecomment-634602993.
=> Remove dead vehicles from selection.

game/ui/base/basescreen.cpp, game/ui/base/researchscreen.cpp, game/ui/base/researchselect.cpp, game/ui/base/vequipscreen.cpp, game/ui/city/alertscreen.cpp, game/ui/city/basebuyscreen.cpp, game/ui/city/basedefensescreen.cpp, game/ui/city/baseselectscreen.cpp, game/ui/city/bribescreen.cpp, game/ui/city/buildingscreen.cpp, game/ui/city/infiltrationscreen.cpp, game/ui/components/locationscreen.cpp, game/ui/general/cheatoptions.cpp, game/ui/general/ingameoptions.cpp, game/ui/general/messagelogscreen.cpp, game/ui/general/optionsmenu.cpp, game/ui/general/savemenu.cpp, game/ui/ufopaedia/ufopaediacategoryview.cpp, game/ui/ufopaedia/ufopaediaview.cpp
Adds missing handling of [Enter] and [KP Enter] to forms with OK buttons.
Additionally unifies handling of form closing hot-keys.
Related to #294.
=> Make forms with OK buttons closable on [Enter].

data/forms/aequipscreen.form, data/forms/researchscreen.form, data/forms/researchselect.form, forms/listbox.cpp, forms/listbox.h, game/ui/base/researchscreen.cpp, game/ui/base/researchselect.cpp, game/ui/general/aequipscreen.cpp
An alternative to #868.
Adds `<autoselect>` option to `listbox`es defaulting to **yes** (current behavior) providing ability to disable automatic selection of a newly added item in case of no previous selection. And sets the option to **no** where previously `AlwaysEmitSelectionEvents` workaround was employed.
Resolves #786.
Resolves #870.
=> ListBox: Drop AlwaysEmitSelectionEvents workaround in favor of AutoSelect setting.

game/state/gametime.cpp
Changes how save games are presented in the menus altering Days field to show total days since 2084-Mar-7 instead of day of month.
=> Show total game days in save game menus.

README.md
Changes AppVeyor badge link to point to the latest master branch build. And adjusts the instruction to advise users to look for the master branch builds.
=> Adjust AppVeyor badge and instruction to point to master branch.

framework/logger.cpp
This uses std::cerr, so should include iostream. It seems on many stdlib
implementations, this was included by proxy, but not guaranteed (and
seems to break on new libc++ versions)
=> Include <iostream> in logger

framework/font.cpp, framework/modinfo.cpp, framework/modinfo.h, library/line.h, library/strings.cpp, library/strings.h, tests/test_unicode.cpp
This allows us to build with c++20 enabled - the biggest changes are the introduction of char8_t for utf8 character streams, and char32_t and similar no longer being implicitly cast-able to other integer types (As they're meant to be utf32 codepoints, not "numbers")
Note this is a /workaround/ - a long-term solution would be to replace the entire UString type with u8string (as they effectively mean the same thing - "utf8-encoded bytes" - and move the helpers we use to free functions (if they can't be replaced by standard library functions).
Unfortunately, pre-c++20 didn't define all the types (e.g. char8_t being distinct from 'char'), so until we move completely to only even newer c++ versions we probably need some level of hackery.
=> c++20 preparation workarounds

.gitmodules, README.md, dependencies/CMakeLists.txt, framework/sound/sdlraw_backend.cpp, game/state/battle/battledoor.cpp, game/state/battle/battleunit.cpp, game/state/city/base.cpp, game/state/city/building.cpp, game/state/city/city.cpp, game/state/city/research.cpp, game/state/city/vehicle.cpp, game/state/rules/agenttype.cpp, game/state/rules/battle/battlemap.cpp, game/state/rules/battle/battleunitanimationpack.cpp, game/state/rules/battle/battleunitimagepack.cpp, game/state/rules/city/vehicletype.cpp, game/state/shared/agent.cpp, game/state/tilemap/pathfinding.cpp, game/ui/base/transactionscreen.cpp, game/ui/components/controlgenerator.cpp, game/ui/general/cheatoptions.cpp, library/CMakeLists.txt, library/backtrace.cpp, library/strings.h, library/strings_format.h
This is a step towards using fmt's new indexed format string API (e.g. "thing: {1} {2}" instead of "thing: %s %s"). Though it still uses the printf-compatible formats for now, at least the fmt library can support both in parallel, allowing us to phase over.
This then is more consistent with boost::locale's formatting API, which is the longterm goal to allow reorder-able translate-able strings in code.
Plus, fmt is proposed to be in c++20 (and accepted - for now :) - so likely to be more 'standard' and 'expected' in c++ going forward (and may even allow us to drop a non-standard-library dependency eventually)
=> Use fmtlib instead of tinyformat

game/state/battle/battle.cpp, game/state/battle/battleunit.cpp
Fix to #849
Civilians are never considered enemies.
Added check for reaction fire to not shoot civilians.
=> Civilians should not appear hostile and not cause reaction fire

game/state/city/base.cpp, game/state/city/building.cpp, game/state/city/vehicle.cpp, game/state/city/vehicle.h, game/state/shared/agent.cpp, game/state/shared/agent.h
The agents and vehicles are marked dead/destroyed and they are cleaned up on next update after they die.
Should fix removing agents and vehicles during iterating through the lists.
=> Fixes for destroyed bases #915

README.md
Fixes image of the lower AppVeyor badge.
Changes upper AppVeyor badge link and image to point to the latest master branch build as well.
Changes TravisCI badge image to point to the latest master branch build.
Updates TravisCI badge link due to CI migration.
=> Adjust AppVeyor and TravisCI badges to point to master branch.

game/state/battle/battle.cpp, game/state/battle/battleunit.cpp
In turn-based mode spotted units remain visible until the end of the turn
=> In turn-based mode spotted units remain visible until the end of the turn

game/state/city/vehicle.cpp
This would previously leave a dangling reference if the vehicle was inside a building and it "died" (e.g. sold or otherwise removed from the game)
=> Clear vehicles from Building::currentVehicles when dieing

game/state/city/agentmission.cpp, game/state/city/agentmission.h, game/state/city/building.cpp, game/state/city/scenery.cpp, game/state/city/vehicle.cpp, game/state/city/vehicle.h, game/state/city/vehiclemission.cpp, game/state/city/vehiclemission.h, game/state/gamestate.cpp, game/state/shared/agent.cpp, game/state/shared/agent.h, game/state/shared/organisation.cpp, game/state/tilemap/tileobject_vehicle.cpp, game/ui/tileview/citytileview.cpp, game/ui/tileview/cityview.cpp
We don't need this indirection, and the mission classes are relatively easy to copy anyway.
=> Make Vehicle and Agent missions direct objects instead of up<Object>

data/scripts/openapoc_base.lua, data/scripts/update_economy.lua, game/state/city/economyinfo.cpp
Fix to #939
Economy update appears to be moved to Lua.
Current price was always multiplied by 1.0.
I am guessing math.clamp function parameters were in wrong order based on how the clamp was called.
Fixed typo in economyinfo.cpp (is it used anymore?).
=> Prices change correctly end of the week

CODE_STYLE.md, framework/fs/physfs_archiver_cue.cpp, tools/lint.sh
Now the travis-ci build uses clang-format-10 we need to reformat everything for the linting pass' sanity.
=> Reformat using clang-format 10

game/ui/base/transferscreen.cpp
This causes an unhandled exception since the {fmt} rework, as it uses the "%s" format specifier for an integer when rendering the usage of stores.
Fixes #961
=> Fix usage formatting string in transfer screen

tools/launcher/launcherwindow.cpp
We don't want to give the launched process arguments, so empty second
arg seems good here?
=> Fix deprecated QProcess:startDetached() use

game/state/gamestate.cpp
Fixes #965. Fixes #973 . 
Added additional validation during update loop. Tested using both saves provided.
=> Economy: fix crash when building was razed

CMakeLists.txt
/permissive- causes errors in <optional> and our constexpr Colour constructors
For now disable it on just that version.
=> Build fix - Workaround bug in visual studio 16.9 compiler

CMakeLists.txt, appveyor-dev.yml, appveyor.yml, tools/CMakeLists.txt
Disable the launcher for now - I think the appveyor CI is timing out trying to build qt5, which is only required for the launcher.
=> Use binary QT5 package for appveyor builds

.github/workflows/lint.yml
If the string was empty (e.g. no range available in the action), the resulting "if [[ -z ]]" is invalid
=> Github action: Fix quoting of strings

data/forms/cheatoptions.form, game/state/gametime.cpp, game/state/gametime.h, game/ui/general/cheatoptions.cpp
In order to simplify some time related events (e.g: end of day/end of week) I propose to add 3 cheats that forwards in-game time directly to one second before the selected time period:
- Go to end of day
- Go to end of week
- Go to end of month
=> Add time related cheats

tests/test_serialize.cpp
This was missing and breaks build on gcc 11 (likely due to some other
library header no longer including it)
=> Add <thread> header to test_serialize

framework/CMakeLists.txt, framework/modinfo.cpp, framework/modinfo.h, framework/translation.h, tools/extractors/main.cpp, tools/launcher/launcherwindow.cpp, tools/launcher/launcherwindow.h, tools/launcher/launcherwindow.ui, vcpkg.json
ModInfos can now list a set of supported languages.
Currently, only the first enabled mod is used to populate this list.
=> Add support to the launcher to select languages

framework/framework.cpp, framework/framework.h, framework/logger.cpp, framework/options.cpp, framework/options.h, tools/launcher/launcherwindow.cpp, tools/launcher/launcherwindow.h, tools/launcher/launcherwindow.ui
- Scale mouse input coordinates to screen size, fixing input in scaled mode (Fixes #222)
- Implement convenience option to auto-scale screen according to reference resolution (currently set to 1280x720) eliminating a need to manually calculate scale values. Enabled by default in non-fullscreen mode to improve first time experience.
=> Implements mouse input scaling, auto screen scaling option

.gitignore, game/state/battle/battle.cpp, game/state/gamestate.cpp, game/state/gamestate.h, game/state/rules/battle/battlemap.cpp, game/state/shared/agent.cpp
- Fix crash caused by agent being removed during GameState::update by delaying agents removal and avoid modifying STL container while iterating over it. TODO: check if any other containers might be handled incorrectly.
- Updated .gitignrore to ignore case for xcom.bin
=> Fix crash when agent in cityscape dies

.gitignore, game/state/battle/battle.cpp, game/state/gamestate.cpp, game/state/gamestate.h, game/state/rules/battle/battlemap.cpp, game/state/shared/agent.cpp, game/state/shared/agent.h, game/state/shared/organisation.cpp
- Fixes issue when recruiting agent during pause at midnight dead agents
with 0 health are available for hire. (Issue #990)
- Caused by refresh of hirable agents, which mark removed agents as dead
but do not removed them from the list. Fixed by forcing agent removal.
- Based on PR #1049
=> Fix midnight zombie agent for hire issue

game/state/city/building.cpp
- Prevents game quitting with error when cargo that wasn't picked up
expires
=> Fix expired cargo

game/state/battle/battle.cpp
At least MSVC 19.29.30133 classes defined local to functions no longer see enum class types defined in the same parent function.
Not sure if this is an MSVC bug, or we were running fast and loose with the c++ spec other compilers aren't as strict about, but a small bit of file-local namespace pollution is probably fine.
=> Fix build issue on new MSVC compilers

game/ui/tileview/cityview.cpp
Another formatting issue - %s can't handle anything that isn't a string
or a custom formatted type.
Fixes #1060
=> Fix crash when clicking on a projectile in the cityscape

forms/scrollbar.cpp
- Fix accidentally moving items when scrolling up or down the list
- Fix incrementing by 2 when clicking to buy or sell items
I assumed that we only want to scroll the vertical scroll bars by using the mouse wheel. Original Apoc did not have any scrolling using the mouse wheel.
#1085 #1084
=> Scroll bar fixes #1085 #1084

appveyor-dev.yml, appveyor.yml
Looks like the version we used has had some download links removed so libiconv (or msys2 that it's build uses) no longer works.
=> Update vcpkg in appveyor

tools/extractors/extract_unit_animation_pack_unit.cpp
This looks wrong, passing an integer to a bool argument and bool to integer argument - noticed when looking over the code.
Not 100% on what this actually does or could break, but the types make it look wrong.
=> Fix switched arguments when extracting strafing when aiming animations

framework/options.cpp
Disabled autoscale. With this option all visible. Without only black screen.
=> Disable autoscale for macOS

game/ui/base/basescreen.cpp, game/ui/base/vequipscreen.cpp, game/ui/tileview/cityview.cpp
At current trying to open the vehicle equip screen with no vehicles leads to an error message and seg fault, and trying to open the agent equip screen with no soldiers leads to issue #1100. I have attempted to fix this by adding preliminary checks to the callback functions for opening the equip screens that check if the player has soldiers/vehicles that they can equip before letting them be opened.
In terms of the implementation I'm not the biggest fan of the duplicated code in the callbacks but I'm not sure how I would go about puling it out into a separate function. Could perhaps be generalized and thrown in gamestate or organisation file but I am not sure if it would be worth it.
=> Avoid opening agent/vehicle equip screens if player has no soliders/vehicles

game/ui/base/recruitscreen.cpp
Not sure if this is the ideal solution but this ensures that the fired agent state is immediately synced with the game state.
=> Fixes #1101

.github/workflows/lint.yml
This PR fixes a syntax issue on the lint workflow and ensures that the github action version is the latest.
This will remove the warning annotation that was showing up on Lint.
=> Lint workflow fixes

game/state/city/agentmission.cpp, game/state/gamestate_serialize.xml, game/state/shared/agent.cpp, game/state/shared/agent.h, game/ui/base/transferscreen.cpp
The transfer screen was teleporting the soldier to Warehouse 2 and then from there he was assigned to move to the correct base. This PR fixes this issue.
Also fixes some typos and lint errors.
=> Fix soldier transfer

game/ui/tileview/battleview.cpp
As mentioned in #1004, the camera does not snap to the unit with leftover movement that needs to be completed. This resolves this by zooming to the position of the unit in question.
=> Fix: Center the screen on the pending unit.

game/ui/base/vequipscreen.cpp
Fixes #694. My OG experience differs from what is explained in the issue. When trying to remove the passenger module with extra soldiers on board, the game throws up a dialog box explaining that you can't remove the module while in use.
Example from OG:
With that being the case, this PR implements this in OpenApoc by checking if the new number of passengers will be higher than the max passengers when the module is removed. If this is the case, the same dialog box is shown.
Example from OpenApoc:
=> Fix removing passenger module left excess passengers on vehicle

game/ui/components/controlgenerator.cpp
As mentioned in #993, the icon showing the number of passengers in a vehicle was off by one pixel. This PR fixes that.
=> fix: move the passenger number icon one pixel left.

game/ui/base/vequipscreen.cpp, game/ui/general/aequipscreen.cpp
Fixes #627. This PR makes the equip screens function as they did in the original game by making it impossible to exit the screen if an item is picked up.
=> fix: Prevent either equip screen from closing when an item is picked up.

game/ui/general/messagelogscreen.cpp
Fixes https://github.com/OpenApoc/OpenApoc/issues/546.
It would appear that when the ScrollBar is created in the MessageLogScreen, it uses the original Maximum value of 10 that is assigned by default. When calling the scrollMax function, it was only scrolling down by 10. This was verified by increasing this initial Maximum value and observing the ScrollBar scroll further down the message history screen. This PR fixes this problem by calling the MessageLogScreen::update function to obtain the correct Maximum value before calling scrollMax.
=> Fix message history screen scrolling

game/state/gameevent.cpp
Addresses #1131.
This PR shortens the "Vehicle Destroyed" message to match the original game.
=> Fix vehicle destroyed message too long

framework/framework.cpp, framework/options.cpp, framework/options.h, framework/sound.h, framework/sound/null_backend.cpp, framework/sound/sdlraw_backend.cpp, framework/sound_interface.h
Lots of samples together just sound like noise, and can have bad corner cases (e.g. after unpausing multiple of the same sample could perfectly overlap making it super loud and clip)
=> Implement a cap on number of concurrent samples

game/state/shared/aequipment.cpp
Caused by trying to normalize a 0 vector
Fix #930 
This is NOT Related and does not fix the following issues: #1007 & #1057
=> Fix CTD by throwing grenade onto same Tile Unit is standing on

game/ui/tileview/cityview.cpp
In the original game, if follow vehicle is toggled and the selected vehicle enters a building, you are free to move around the map and the follow vehicle toggle is essentially turned off. In OpenApoc, the camera stays locked on to either the selected vehicle or agent even if they are in a building. This PR adds the behaviour from the original game, plus removes the ability to follow an agent if they are just sitting in the base. The ability to lock on to an agent in the base seemed pretty useless, so now the follow toggle will only follow a moving vehicle or agent within a moving vehicle.
As a side note, it seems the original game does allow you to follow an agent even when in a vehicle. I'm guessing that is a QOL addition to OpenApoc. If I have unintentionally removed any other QOL …
=> Fix follow vehicle or agent when in building

game/ui/tileview/cityview.cpp
Fixes #1142.
This PR checks if an agent is in a vehicle when the return to base button is pressed from the agent menu. If true, nothing will happen when pressed.
Relevant code, the rest is linting:
```
agentForm->findControl("BUTTON_GOTO_BASE")
->addCallback(FormEventType::ButtonClick,
[this](Event *)
{
auto a = this->state->current_city->cityViewSelectedAgents.front();
// Don't return to base if in a vehicle
if (!a->currentVehicle)
{
orderGoToBase();
}
});
```
=> Fix agents returned to base while in vehicle

game/ui/components/controlgenerator.cpp, game/ui/components/controlgenerator.h
Fixes #306.
Checks if the vehicle target building is the home building and places the X as per vanilla.
=> Fix add X when returning to base

data/forms/mainmenu.form, game/ui/general/mainmenu.cpp
Removes options menu from main menu. Since I didn't get a ton of feedback on this issue, I'll just drop this here in case a consensus is reached. Code commented out instead of deleted to seem more temporary.
=> Remove options menu from main menu

game/ui/general/ingameoptions.cpp
Partially fixes #1148.
Adds tooltip text to the in game options menu. Tooltips for agents and vehicles still a work in progress.
=> Add tooltip message to the in game options menu

forms/graphicbutton.cpp, forms/graphicbutton.h, game/ui/general/transactioncontrol.cpp
In the original game, the horizontal scroll bars in the transaction screen moved one item at a time when clicked. In OpenApoc, the scrollbars move depending on the amount of items in the list. This PR fixes this issue by separating the vertical and horizontal scrollbars in the transaction screen and setting the button click to move add or remove exactly one item each time.
=> Fix transaction screen scrollbar multiple items per click

game/ui/components/controlgenerator.cpp
Fixes #1154.
The green X was not being added when a vehicle returned from a mission, or more specifically, when it was ferrying cargo. This PR fixes that by checking if the vehicle is on a ferry mission and adds the X.
=> Fix add X to vehicle icon when ferrying cargo to base

game/ui/components/controlgenerator.cpp
Fixes #1148.
This PR fixes the tooltip text for agents, vehicles, and organizations. Previously it only worked when hovered over the frame of the icon. In addition, the tooltip text is now working for agents in the battlescape.
=> Fix tooltips not working correctly in cityscape and battlescape

game/state/city/base.cpp, game/state/city/base.h, game/ui/base/basescreen.cpp
Fixes #571.
Adds a check to make sure the alien containment facility is either empty or missing and alerts the user as per vanilla.
=> Fix alien containment screen opening when empty or gone

game/ui/base/vequipscreen.cpp
As mentioned in the recent stream, the count labels in the vehicle equip screen are not centered. This PR fixes that.
Before:
After:
=> Fix center count label under equipment

game/state/city/vehicle.cpp
Fix #1168 
Prior trying to entering building, check whether already in a building, and if this building and target building are the same. If yes then throw the error, if not (like it was the case in the Issue reported on Discord by DOR Jan) then create a mission to send the vehicle to the correct building
=> Fix Vehicle trying to Enter Building not currently at

game/state/city/vehicle.cpp, game/ui/general/vehiclesheet.cpp
Fixes #1164.
When enforce cargo limits is turned off, it only counts cargo coming back from a mission. This PR extends the option to include picking up cargo in the cityscape. When off, a single vehicle can pick up an unlimited amount of cargo from a building. This is limited to only player owned vehicles and not the transtellar transports in the city. When cargo limits are disabled, the vehicle will only show the cargo that is onboard and no max cargo number.
=> Fix cargo limits not being enforced in the cityscape

game/state/city/vehicle.cpp, game/state/city/vehiclemission.cpp
Fix #1168 
Reverted changes from PR #1169 and added check if a vehicle to be rescued is visible on the map and not within a building. If so the vehicle to be rescued will die and not rescued. Prevents errors observed. Add. might only be an issue when using a savegame created w/ earlier versions, still has to be confirmed by OG Bug Reporter
=> Prevent rescuing vehicles not visible on the map

game/ui/components/controlgenerator.cpp
Fix #1171 the CDT part but now the UI incorrectly displays two green "X"'s instead of One.
Maybe @Kurtsley could have a look into this
=> Fix CTD when selecting X-Com Vehicle Tab

data/common_patch/gamestate.xml, data/common_patch/gamestate/agent_types.xml, game/state/gamestate.cpp, game/state/gamestate_serialize.xml, game/state/rules/agenttype.h, game/state/shared/agent.cpp, game/state/shared/agent.h, game/ui/tileview/cityview.cpp, tools/extractors/extract_agent_types.cpp
This MR solves issues #1110  and #573 
- back to former 10 soldiers at the new game start (no missing equipment for soldiers #573)
- only humans as soldiers at the new game start (like in OG - solves #1110
=> Fix agents on init

forms/listbox.cpp
On the previous version of master, I could not enter any skirmishes as the list of maps was empty.  This pull request fixes an error in listbox.cpp that was introduced in the last merge into master.  That previous merge had changed the line
> ctrl->Size.y = ItemSize;
to
> ctrl->Size.y;
but this second version doesn't do anything, so I reverted it back.  After this change, I can again enter skirmish mode.
=> fix to listbox.cpp error

data/forms/aequipscreen.form, data/forms/recruitscreen.form, data/forms/researchscreen.form
This addresses an issue that has been bothering me where the agent and scientist names have inconsistent spacing. 
The research screen shows this problem.
My first idea was to simply insert a newline between the agent's first and last name upon creation:
```
agent->name = format("%s\n%s", firstName, secondName);
```
This worked, however a logwarning message was thrown each time a name was hovered:
Not wanting to deal with that problem (if it is an actual problem) I simply changed the forms to shrink the width of the lists containing the names. This solves the problem, although I haven't seen every possible name combination, and does not have a negative impact on gameplay. You don't notice the smaller width because you always click directly on or very near the agent.
After:
Note: This does …
=> Fix gap between name and skill

forms/listbox.cpp, game/ui/general/optionsmenu.cpp, game/ui/skirmish/mapselector.cpp
Since the latest merge broke the multi line history message I figured I'd fix up what I missed. This removes the ItemSize again and fixes the problem with the skirmish map selector not showing up. It also takes care of items in the now defunct options menu not appearing. Apologies for not catching this earlier, all instances of listbox should now be taken care of.
=> Fix skirmish mode map list

forms/control.cpp
Fixes #1181.
The tooltips now render inside the screen at all times!
=> Fix tooltips rendering off-screen

data/forms/battle/battle_rt_tab3.form, game/ui/tileview/battleview.cpp
Addresses #1072.
I'm putting this PR forward as a step in the right direction, but more work has to be done. As discussed in issue 1072, the wording of the proximity mines is a bit confusing. This changes the wording of Activates Now to Detonates Now.
Ex.
The issue of delay == 0 was some sort of rounding or math error and has been corrected. The delay slider now reads correctly in seconds and counts up by one quarter second until 7.5. To match the original game timer length of 7.5 seconds, I had to add one to the max value of the delay slider. The delay slider now maxes out at 30 instead of 29.
Ex.
I noticed that the "Activates Now" string is present in the ufo_string translation files and adding another phrase without translating it could be a problem. This was not tested in another …
=> Fix the confusing naming of proximity mine delay

game/state/gamestate_serialize.xml, game/state/rules/city/organisationraid.h, game/state/shared/organisation.cpp
Addresses #999.
This implements the formula layed out in this issue. The vehicle count in a raid is now an orgs number of buildings plus number of vehicles -1 divided by number of buildings. The max amount of vehicles in a raid is 5. As for opening this up to modding, I'm not exactly sure about that process and could use some advice.
=> Fix raid vehicle number now variable up to 5

framework/options.cpp, framework/options.h, game/state/city/base.cpp, game/state/city/building.cpp, game/state/city/building.h, game/state/gameevent.cpp, game/state/rules/battle/battlemap.cpp, game/ui/general/ingameoptions.cpp
Partially fixes #1067.
Every case of an empty base being attacked was covered except the case in Building::detect. This adds a check for an empty agent list and automatically destroys the base if true. I also added a city notification to alert the player that the base has been destroyed. I believe this adds the same functionality as the original game.
=> Empty base will now be destroyed with message

game/ui/city/alertscreen.cpp, game/ui/tileview/cityview.cpp
Addresses #1195. 
So this is both an actual problem and a control problem. As for the first part, it was not possible for an agent to call a taxi from the alert screen when clicking on the investigate button. This PR fixes that issue. With the option on, all soldiers will now call a taxi to take them from the base to the target building. The second part was when the soldier was stuck at the building halfway to the target. If you hold either control and click the target building, the soldier will call a taxi. I think this is a bit obscure. Maybe a better option would be to alert the user and give an option to call the taxi from a messagebox? I thought about letting the soldier automatically call a taxi if the option is checked, but this would happen no matter how short the distance to the …
=> Fix soldiers can call taxi from alert screen

framework/options.cpp, framework/options.h, game/ui/general/ingameoptions.cpp, game/ui/tileview/battleview.cpp
Addresses #1208.
Adds the option to select squads with a single click. This not quite what the vanilla game did however... In OG Apoc, clicking a squad with the mouse acted as OpenApoc does now while using the number keys instantly zoomed to the squad. In this case, I felt it wasn't necessary to bring this functionality back as we can have the best of both worlds with the in-game options.
=> Added the option to select squads with a single click.

game/ui/tileview/battleview.cpp
Just a small UI tweak that changes the battlescape cursor to normal when the inventory screen is opened. This also does the same when the options menu is opened using the button instead of the escape key.
=> Change the cursor to normal when inventory or options menu are opened

game/state/battle/battle.cpp, game/state/battle/battleunit.cpp
Addresses #1218.
There are two problems happening here. If you prime a grenade for any amount of time, drop it, then pick it up the game will crash when the timer runs out. If you pick up the grenade before it explodes and then end the mission, it will crash the game at the beginning of the next mission unless unequipped. The main problem stems from a unit update function in battleunit.cpp and the explode function in aequipment.cpp. It appears the update function is called every tick and iterates through each units inventory as part of the update process. The explode function will remove the grenade once it has exploded. When the grenade is place back into the inventory and explodes, the explode function will remove the equipment from the inventory and cause the crash.
The update function …
=> Fix grenade related crashes

game/state/battle/battle.cpp, game/state/battle/battleunit.cpp, game/state/battle/battleunit.h
Looking at the weapon and ammo related bugs.
I didn't see a final decision regarding if clips should be filled after a mission or left partially filled and dealt with accordingly. I see there is an advanced inventory controls option that mentions unloading clips, but I don't see this put to use.
This would reload empty weapons at the start of the battle, which would solve #1210. Is this OG behaviour? If not it could be an option.
This also addresses #607 by recharging all equipment that needs to be recharged after a mission. I tested this on the disruptor shields and the rechargeable sniper from the EWM.
=> Empty weapons reload at start of battle

game/state/gamestate.cpp
FINALLY fixes #1112. This also applies to destroyed bases.
=> Destroyed vehicle messages now point to last position

game/state/battle/battle.cpp
Exception could be thrown if exiting battle with no rechargable weapons.
=> Fixed bug exiting battle with no rechargable weapons

game/ui/tileview/citytileview.cpp
A random fix for a crash I stumbled upon when playing with debug hotkeys
=> Fixed a formatter crash when pressing F3 in debug mode (show walkmode)

game/ui/general/savemenu.cpp
Fixes #1167.
I'm not exactly sure how the system works, but this replaces StageCmd::Command::Push with StageCmd::Command::REPLACEALL. This is consitant with how the "Abandon game" button works, which frees up all memory before starting a new game. When loading a game, all stages are cleared and replaced. Seems to work.
=> Fix memory leak when loading save

data/forms/moreoptions.form, framework/options.cpp, framework/options.h, game/ui/CMakeLists.txt, game/ui/general/ingameoptions.cpp, game/ui/general/ingameoptions.h, game/ui/general/moreoptions.cpp, game/ui/general/moreoptions.h
Would like some feedback on something I've been working on. I think it is time to ditch the more options list and move to a different options menu. When trying to add features such as a map scroll speed scrollbar, there is no room left on the original options menu. 
Here is the rough example I'm working with:
So far the options list has moved to this new menu, but you can see there is now room to add different options besides a checkbox in a list.
If a consensus agrees this would be a good idea moving forward, the menu could be spruced up with a frame around the list. I'm also thinking of moving some of the more important options out of the list and adding a vanilla mode toggle that would toggle all options to simulate a vanilla experience.
Let me know what you think.
TODO:
=> Moreoptions menu

tools/launcher/launcherwindow.cpp
This removes the MAX_DISPLAYS variable and instead checks the number of attached displays when the launcher starts.
Two questions:
- Was the MAX_DISPLAYS variable chosen for a reason?
- Should this be kept but replaced with the displays.count() variable?
https://github.com/OpenApoc/OpenApoc/blob/e3a41f96078237cf31aee3337afa6dfcd52674c8/tools/launcher/launcherwindow.cpp#L218-L221
I figured no for both so I removed them.
=> Auto detect number of displays in the launcher

framework/options.cpp, framework/options.h, game/state/city/vehiclemission.cpp, game/ui/general/moreoptions.cpp, game/ui/tileview/cityview.cpp
Addresses #696. 
This allows ATV type vehicles to initiate UFO missions, but not recover UFOs. If an ATV type vehicle approaches an unmanned UFO, it just returns to base. This could be done better, maybe not even try in the first place. Should they also be able to recover the UFOs?
=> Allow ATV type vehicles to initiate UFO missions.

game/state/battle/battle.cpp
Fixes this annoying issue that crops up sometimes after an agent dies in battle:
This was happening if a selected agent in the cityscape died in battle. The gamestate was updating the agents and expecting this selected agent to still exist. This clears the selected agents before a battle to make sure this can't happen.
=> Fix selected agent dying in battle causes error

game/ui/tileview/cityview.cpp
Addresses #991 among others.
This delays the switch from the alien dimension until all projectiles have died and all UFOs have crashed. Has been lightly tested and seems to function.
Should this rule apply to anything else? XCOM craft too?
=> Delay the switch from alien dimension to clear projectiles

data/scripts/openapoc_base.lua, framework/options.cpp, game/state/luagamestate.cpp
The mod ScriptsList (scripts ran at mod init) didn't use the virtual FS, so would not load if the $(CWD) didn't match the data directory.
This caused warning as scripts failed to load in the tests, as well as if any mod overrides the file.
Note that this means that scripts loaded through dofile() in lua are now relative to the data/ directory and can be replaced by mods overwriting the name in their own data.
=> Load lua scripts using virtual FileSystem

data/forms/aequipscreen.form, data/forms/battle/prestart.form, data/forms/sheet_agent_history.form, data/forms/sheet_agent_profile.form, data/forms/sheet_agent_stats.form, game/state/battle/battle.cpp, game/state/battle/battleunit.cpp, game/state/battle/battleunit.h, game/state/shared/agent.cpp, game/state/shared/agent.h, game/ui/base/recruitscreen.cpp, game/ui/base/recruitscreen.h, game/ui/base/transactionscreen.cpp, game/ui/base/transactionscreen.h, game/ui/base/transferscreen.cpp, game/ui/battle/battleprestart.cpp, game/ui/battle/battleprestart.h, game/ui/general/aequipscreen.cpp, game/ui/general/aequipscreen.h, game/ui/general/agentsheet.cpp, game/ui/general/agentsheet.h
Hi OpenApoc Team,
First up  I apologise in advance for my dyslexia.
Thanks for the awesome work you guys are doing with this project, it's amazing. I started hacking a couple of weeks ago and I was able to get something working for #1212 the agent history screen.  I'm not a C++ dev so I'm sure there are many issues here but I figured I'd throw up a PR just for shits and gigs.  I have had a lot of fun working on this.  Throw the book or ignore it altogether. I won't be offended.
---
A breakdown of the changes I have made:
* Fixed a id attribute in `aequipscreen` form
* Created a new agent history form
* Broke a profile form out from agent stats so it can be shared between the new history form and the existing stats form
* Added an activatedInSquad member function to battle unit in order to …
=> Issue 1212: Added agent history screen

game/ui/debugtools/formpreview.cpp
Currently, the labels in the debug tools form preview are not visible. This change sets a height and width of the labels so they can now be seen.
Before: 
After:
=> Bug Fix : Form debugger selection labels

data/forms/sheet_agent_history.form, game/state/shared/agent.cpp, game/state/shared/agent.h, game/ui/general/agentsheet.cpp
* Added medals to the agent history form
* Added code that will hide the medals according to agents current medal tier
* Added stub method to agent that will always return a tier of zero.
Note: This PR should not change anything that the player can see as the medal tier will always be set to zero. In the above screenshot, the medal tier has been hardcoded to 5 for illustrative reasons. This is intended as a precursor for a bigger set of changes around agent experience.
=> Added medal rendering

data/forms/city/debugoverlay_city.form, game/ui/tileview/cityview.cpp
I have finally started to narrow down the stuck vehicle bug. While I continue to sort it out, I am going to add this debug option to unfreeze vehicles that become stuck during combat in the cityscape. Almost every large battle that breaks out has at least one stuck vehicle that prevents the player from using ultra-fast speed. This makes sure the the vehicles tickstoturn value is not 0, which fixes the issue. Anyway, shift + left click on a vehicle in debug mode will accomplish this.
=> Add an option to unfreeze vehicles in game.

data/forms/city/debugoverlay_city.form, game/ui/tileview/citytileview.cpp, game/ui/tileview/citytileview.h, game/ui/tileview/cityview.cpp
This adds a debug option to view what each vehicle is currently targeting. I used this while trying to fix the stuck vehicle problem. It turned out that targeting wasn't the problem, but this is pretty useful. The last addition to the debug overlay was being cut off so that was fixed as well.
Green line = XCOM vehicle is targeting an enemy.
Red line = Enemy is targeting an XCOM craft.
Yellow line = The two are targeting each other!
=> Add vehicle target debug view plus fix debug overlay cutoff.

game/state/city/vehiclemission.cpp
I think I finally narrowed this problem down. The vehicle was attempting to sidestep to another location when it had 0 tickstoturn. Since it was trying to turn but couldn't, this froze the vehicle in place. This checks if tickstoturn is over 0 before sidestepping. I will admit that I can't test every situation that could happen so this could have unforeseen consequences. I have included the save I was using to test, it is a gigantic firefight. One or more vehicles would get stuck every other time I played on average before the fix. So far the fix has stopped any vehicles from getting stuck for 30 plus playthroughs of the fight.
[save_stucktest.zip](https://github.com/OpenApoc/OpenApoc/files/13465294/save_stucktest.zip)
=> Fix vehicles getting stuck in cityscape

game/ui/tileview/cityview.cpp
Fix #1258. View now updates when org button clicked.
=> Refresh organisation list when corresponding button is clicked

game/ui/ufopaedia/ufopaediacategoryview.cpp
Clicking the info button in the ufopaedia will now actually show the list of items.
=> Fix list not appearing in ufoaedia.

data/forms/city/debugoverlay_city.form, game/ui/tileview/cityview.cpp, game/ui/tileview/cityview.h
Holding V plus left click will now unfreeze a stuck vehicle. Added the deprecated comment because this should only work on vehicles that are stuck in old saves, the problem is hopefully resolved moving forward. I also noticed that quickmind was wondering about the crash and destroy vehicle commands. They don't seem to be documented, but they exist in the code. I relabled the debug overlay to fix this.
=> Rebind fix stuck vehicle debug

game/ui/components/controlgenerator.cpp
Per the stream, agent shields now show current health until the shield is gone. I messed around with vehicles but they work differently because of the recharge. Should they be included?
=> Fix agent shields now show current health

data/forms/creditsmenu.form, data/forms/mainmenu.form, game/ui/CMakeLists.txt, game/ui/general/creditsmenu.cpp, game/ui/general/creditsmenu.h, game/ui/general/mainmenu.cpp
Here is the first draft. Some thoughts:
I have not figured out how to do two columns and still have text alignment on both. I can do a split list, but the names are all over the place. That is why it is a single column down the middle. The github contributors will probably add some length to the menu. I noticed that a couple people on the discord list seem to be using their real names, I left them in for now but I don't know the rules. The separators between sections are crude underlines because I can't figure out how to get an image to show in the listbox yet. If someone appears on the developer and programmer list, I left them off the programmer list. I kept duplicates on the testers and translators list because that seems to be a seperate job.
=> Add simple credits menu

game/state/city/vehicle.cpp
I noticed the vehicles traveled in a jerky motion when changing altitude without a mission. This seems to correct that although I'm not sure how often this even happens.
See video - https://youtu.be/gsdKiVrhCrM
=> Fix vehicle now travels smoothly in z axis

game/ui/base/researchscreen.cpp
If you recruit a scientist, they immediately  show up in the unassigned agents list and can be assigned to a project even though they aren't physically at the base.
As you can see, I have assigned Steve Green but he is in another building.
I checked OG, it seems they don't show up in the list until they arrive at the base. Let me know if there is some reason for this that I can't think of.
=> Fix scientists able to be assigned when not at base

game/state/city/vehicle.cpp
This has bothered me for a while and I'm not sure it's an OG function. When I'm trying to return a vehicle back to the base and it's in a firefight, it keeps dodging which prevents it from getting home as fast as possible. I think there should be some option that a vehicle can simply run away from a fight without dodging. 
In this PR, vehicles will run straight home if:
- The vehicle is returning to base
- The attack mode is set to either defensive or evasive
I would like some feedback on this, maybe they should run home if aggressive? Maybe this should just stay the way it is?
=> Add vehicles don't dodge when returning home

README.md, framework/CMakeLists.txt, framework/filesystem.h
We don't support pre-c++17 compilers anyway, so we only need std::filesystem.
=> Remove boost::filesytem support

game/state/battle/battle.cpp, game/state/city/city.h, game/state/gamestate.cpp, game/state/gamestate_serialize.xml, game/ui/components/controlgenerator.cpp, game/ui/tileview/citytileview.cpp, game/ui/tileview/cityview.cpp
Addresses #1262 
This separates the tabs in the cityview into separate lists, allowing them to function individually. The follow vehicle is based on which tab is open, so it only works when the vehicle or hostile vehicle tabs are open. The Scientists can now be selected and monitored as in OG.
I may leave this as a draft for a bit while I continue to think about how to optimize this. Everything is basically being done multiple times now where it was just once before. I'm sure some of the vehicle logic could be condensed, we'll see. The most important thing is if this works just like the OG. On the surface, it seems to work, but there is room for things to break as usual. Please throw everything you have at this PR to try to break something.
=> Add multi select for agents and vehicles

game/state/gamestate.cpp
As in OG, vehicles now reload every 5 minutes instead of instantly. Because of how the event system works, the vehicles will be reloaded in 5 minutes, but the message won't be sent until 10 minutes. That is above my paygrade as they say. There was also a redundant cargo update that was removed. It was called every 5 minutes even though it is also called every second.
=> Change vehicle reload time to every 5 minutes

game/ui/tileview/cityview.cpp
Simple fix to bring in line with OG. The training button should not be checked when no agent is selected.
=> Fix training button unchecked when no agents selected

game/ui/tileview/cityview.cpp
More UI stuff. All tabs in the cityview should now update when clicked. Fired and hired agents now show up instantly. Vehicle stance and height is now blank when no vehicle is selected.
=> Fix tab forms update when clicked, no vehicle stance when not selected

game/state/city/building.cpp, game/state/city/vehicle.cpp, game/state/city/vehicle.h
I noticed in the QM stream that when transtellar was attacked, every single space liner and taxi came out to patrol. I checked OG and found that those vehicles don't come out and try to attack as they have no weapons. This PR checks each vehicle in the building when attacked and only sends out vehicles with weapon slots.
=> Fix unarmed vehicles patrolling when attacked

game/ui/base/vequipscreen.cpp
Addresses #1285
Now vehicles cannot equip items before they are researched. I assume the "You must research Alien technology before you can use it." message will work?
=> Fix vehicles could equip unreasearched equipment

game/state/city/building.h, game/state/gamestate.cpp
Adds a check that makes sure the player base is not the same building that the aliens start in.
=> Fix aliens starting in player base on new game

game/state/gamestate.cpp, game/ui/tileview/cityview.cpp
Attempting to fix the recent missing agent message, just a guess on my part. The civilian list was not being updated when agents were fired, this could cause issues. The soldier list doesn't need this for some reason, they will drop off when killed or fired. I left a logwarning message I used in debugging in the code, this removes it as well.
=> Attempt to fix missing agent message

game/ui/tileview/cityview.cpp
Addresses #1295 
The vehicle stance check has been moved into the update function instead of just checking when clicked. This shouldn't be needed for agents since that list gets cleared before every mission to prevent missing agent errors.
=> Fix empty vehicle stance after mission

game/ui/base/transactionscreen.cpp
Addresses #1301 
The profile form wasn't being cleared when switching agent types, now it is.
=> Fix overlap on transfer screen

game/state/shared/organisation.cpp, game/state/shared/organisation.h
I figured this should probably be added because we are seeing massive numbers of space liners in late game saves. I picked the number 16 randomly, obviously it could be changed.
=> Limit space liners to prevent late game slowdown

data/forms/city/debugoverlay_city.form, game/ui/tileview/cityview.cpp
In old saves, there seems to be a build up of space liners that causes the game to run slowly on the cityscape. This option clears all space liners from the city so more can be sent. Since the max is 16 liners per spaceport, none would be sent unless the existing ones were cleared. Maybe this should be automatically check when loading a save?
=> Add option to clear space liners

game/ui/tileview/cityview.cpp
This should fix the issue with the clear liners debug command. Now the liners in the spaceports get removed as well.
=> Fix clear liners debug command

game/ui/tileview/cityview.cpp
The current system doesn't seem to account for multiple bases and multiple scientist selections. This is how it works in this PR:
This is dependent on the tab selected eg. BioChem, Physics, Engineering.
- If a scientist is selected, it works the same. The lab that the selected scientist is working in will be shown.
- If no scientist is selected, the matching lab at the current base will be shown.
If a scientist is selected in another tab, they are ignored. Not sure this is OG.
=> Fix lab choice when no scientist selected

game/state/battle/battleunit.cpp, game/ui/tileview/battletileview.cpp
Addresses #849.
Removes hostile unit spotted messages from civilians and prevents the selection box from targeting civilians as hostile.
The previous attempt to fix didn't work because the check for civilian AI didn't work correctly when they were panicking, which they do quite often. This doesn't touch the negative effects of killing civilians, it will still hurt your status with the civilian org.
=> Fix civilians appearing as hostile on battlescape.

game/state/city/vehicle.cpp
Addresses #1350.
Interesting bug, the game was trying to push a NotEnoughFuel event but was unable to because the engine had no owner. This only happened at a base with 0 fuel and the vehicle's engine was removed and replaced. It no longer crashes, but the NotEnoughFuel message still does not show up. There has been instances of messages not appearing in the past so this may be a separate issue.
=> Fix crash when trying to refuel at base with no fuel.

framework/options.cpp, framework/options.h, game/state/battle/battleunit.cpp, game/state/shared/aequipment.cpp, game/ui/general/moreoptions.cpp
Addresses #1340.
Weapons with multiple ammo types should only reload the previously loaded type or the weapon is considered out of ammo and must be manually loaded.
Tested lightly, did not seem to mind weapons with one ammo type or none such as the mind bender. Probably should be run through a late game scenario with many different weapon types. The problem was the "lastLoadedAmmoType" didn't exist unless the weapon was manually loaded in battle. This forced me to assign a value to it if the weapon didn't need to be reloaded at the start of the battle. This could in theory cause issues with different ammo types.
=> Add option to only auto reload same ammo type.

game/state/rules/battle/battlemap.cpp
If a facility was somehow out of bounds the battlescape generation would go off into the weeds over the end of an array, so this instead prints a big ERROR and bails instead
=> Don't crash on invalid base battlescapes

game/state/city/vehiclemission.cpp
This didn't return a valid value if the target is reachable, so could return junk and do... who knows what
=> Fix VehicleTargetHelper::isReachableForRecovery if reachable

data/forms/city/debugoverlay_city.form, game/ui/tileview/cityview.cpp, game/ui/tileview/cityview.h
Addresses #1316.
Adds an option (minus key in debug mode) to destroy selected vehicles on the map or in the vehicle tabs. This replaces the clear space liners debug option as it shouldn't be an issue moving forward. The unfreeze vehicle in cityscape option has also been removed for the same reason.
=> Add debug option to destroy selected vehicles, clean up debug options

framework/options.cpp, game/state/city/vehicle.cpp, game/state/gameevent.cpp, game/state/gameeventtypes.h
Address #1287.
Adds a SomethingDiedEvent message when a module is scrapped after a vehicle is recovered. Adds a disclaimer to the tooltips for crashing vehicles explaining the risks.
One example, all four have the same message added.
=> Add message when module lost on recovery.

data/scripts/update_economy.lua
Addresses #1070.
I think I have tracked down the issue. I believe it is an error in the update_ecomony.lua script that deals with other orgs buying Xcom produced goods each week.
Based on the lua error I was seeing plus some trial and error, this only happened when there were Xcom produced goods on the market in small quantities. It could be reproduced by:
- At game start, quickly produce some bio transport modules.
- Sell at least one.
- Skip to the end of the week.
- Error is thrown (60 percent of the time), some items don't restock.
In order to get this to happen every time, line 23 can be changed to if r < 100.
When the currentStock is set to lastStock * 80 / 100, or * 66 / 100, the resulting number is a float if the currentStock is small enough. I believe this is the root cause of …
=> Fix weekly stock not updating under certain conditions

game/state/gametime.cpp
Addresses #1299.
The new day was starting at 00:01 instead of right at 00:00. This also had an effect on setting the correct hire dates for new hires. If anyone can see a reason this was done originally, let me know.
=> Fix day starting after 00:00.

game/state/battle/battleunitmission.cpp
The wrapper  BattleUnitTileHelper::canEntierTile function never initialized some values, which could be used by the child function, so could cause valid paths to be rejected due to junk memory values.
=> Fix battleunit pathfinding with unset memory

game/ui/general/aequipscreen.cpp
Addresses #1296.
I was poking around at the agent equip screen code and I may have accidentally fixed the disappearing item problem. I noticed that grenades could be loaded into weapons, so I fixed that by only allowing ammo type equipment to be loaded (sounds obvious).
https://github.com/OpenApoc/OpenApoc/blob/0864ff5ccc0d88969f234dfaf7df3a239144c9e3/game/ui/general/aequipscreen.cpp#L1445
I believe this line in the adding ammo code was causing some items to disappear. Items like the medkit have 0 ammo while grenades have 1 ammo. Any item that got to this point in the code with 0 ammo would be nullified, causing it to disappear forever. The grenades, having 1 ammo, were loaded into the weapon, causing the logerror message.
While this needs more testing with many different item …
=> Fix various equipment placement issues.

game/state/savemanager.cpp, game/state/savemanager.h, game/ui/general/savemenu.cpp, game/ui/general/savemenu.h
Fix #1347
After discussion in issue thread, I implemented the following logic:
- If writing name in first slot
- If no savefile exists with same name, then create savefile
- If savefile found, open overwrite messagebox
- If writing in existing slot, open overwrite messagebox
I also encapsulated overwrite messagebox call in `SaveMenu::askUserIfWantToOverrideSavedGame`
=> Ask if uses want to overwrite save file when creating save with existing name

game/state/city/base.cpp, game/ui/base/transactionscreen.cpp
This partially solves issues #1302 and #608, since brainsucker pod is not being considered in either alien containment usage calculation or aliens listing, but we still have duplicated aliens.
I also tried to simplify usage percentage math.
=> Remove brainsucker pod from alien containment

game/state/battle/battle.cpp
Most likely addresses #1377.
While testing why the vehicle wasn't returning to base in the issue, I found that vehicles with no loot won't automatically return to base. It looks like the wrong variable was used when assigning a null cargo to returning vehicles. I'm not exactly sure if this was the problem in the issue, but I have run the mission in the save and the vehicle returned to base. The save immediately following the mission in the cityscape doesn't address the issue as the vehicle is assigned the return to base mission in the battlescape.
=> Fix vehicles not returning to base empty after mission

game/ui/tileview/cityview.cpp
The event contained a VehicleType ID, but was indexing the Vehicle list to get the name, which wasn't correct.
Should fix #1378
=> Fix crash on "Vehicle manufacturing halted" message

game/state/city/base.cpp, game/ui/base/transactionscreen.cpp
After discussion in https://github.com/OpenApoc/OpenApoc/pull/1374, it was decide to revert changes made in https://github.com/OpenApoc/OpenApoc/pull/1372
Now Brainsucker Pod is being listed again at Alien Containment screen:
=> Removing filters that removed Brainsucker Pod references.

game/ui/general/moreoptions.cpp, game/ui/general/moreoptions.h
This is a partial fix addressing #1319
1. Add MaxTileRepair and SceneryRepairCostFactor settings and its values to Cityscape Options list
2. Unifying identic logic instructions related to Battlescape Options and Cityscape Options
As you can see, this PR is just a partial fix since it does NOT allow the update of these settings values. But since this already adds a lot of updates, and since it seems that to complete this task it will be necessary to create a new form for numeric values - int and float - I decided to push this PR before doing any further work on this.
Obs.: I created lists to store settings name that are not bool, but either int or float. Please let me know if there's any better way to get these settings value instead.
=> Add City Repair settings to More Options screen

framework/options.cpp
Updated ATV option string, like described in #1388
=> Updated ATV option string

game/ui/base/transactionscreen.cpp, game/ui/general/transactioncontrol.cpp, game/ui/general/transactioncontrol.h
Fixes https://github.com/OpenApoc/OpenApoc/issues/608#issuecomment-502384799
Before rendering transaction control list, set if they are visible based on index and stock conditions. Also isolated condition checks at `Trade.isActive()`
Before:
After:
Obs.: as you can see in the second image, the scrollbar is rendered even if the aliens list is smaller than the transaction view.
=> Checks if trade state is active, hides it from rendered list if not.

game/state/savemanager.cpp, game/state/savemanager.h, game/ui/general/savemenu.cpp, game/ui/general/savemenu.h
Fixes https://github.com/OpenApoc/OpenApoc/issues/1387
PR https://github.com/OpenApoc/OpenApoc/pull/1371 removed feature of renaming existing save files. In this PR it is being added again with the following behavior:
- When selecting an existing savefile and saving with same name, the savefile will be overwritten
- When selecting an existing savefile and saving with a different name, the savefile will be overwritten and renamed with new name
- When creating a new savefile with same name as existing one, the existing savefile will be overwritten
Minor refactorings:
- Updated `getSaveGameIfExists` to return an `optional` instead of `shared_ptr`, and updated references properly
- Updated some parameters and variable declarations with `const` and `auto` references whenever possible
=> Issue 1387: restored renaming savefile feature

game/ui/general/moreoptions.cpp, game/ui/general/moreoptions.h, library/colour.h
Another partial fix addressing https://github.com/OpenApoc/OpenApoc/issues/1319
Adds feature to update "MaxTileRepair" and "SceneryRepairCostFactor" values at More Options screen:
- Updates can be done either via pressing buttons up and down, or manually inserting numeric values.
- Both fields validates input and allows only numbers; "percentage" field also allows dot for decimal places
- Values limit set from 0 to 100
**Known bug:**
When clicking an input field, there's no way to unselect it, so if you click on both fields, they will be selected and editable at the same time. I couldn't find a way to unfocus the text field after clicking on it and some comments in the code suggests that there's no such feature for text edit fields right now. If that's the case, then the text edit field …
=> Adding buttons to new numeric options

game/state/battle/battle.cpp, game/state/shared/agent.cpp
I think the no agent error has been narrowed down. When an agent is killed in a base defense mission, the game would sometimes crash immediately after the mission or when a save is reloaded after that point. It seemed to be the updateCargo function of the base that was causing the issue. 
The killed agents were still technically current agents in the building and the no agent error message was thrown. Obviously the difference with a base defense mission versus any other mission is the agents fighting never leave the building when done. When a typical mission is complete, the agents are loaded onto the vehicle they arrived in and are no longer current agents in the building. It looks like this also applied to soldiers that were killed along with scientists, I am surprised this didn't come …
=> Fix no-agent error on base defense mission.

game/state/battle/battle.cpp, game/ui/base/transactionscreen.cpp
Fixes #1302 and #608
Aliens in containment list were appearing duplicated whenever an alien type exists in more than one base.
Before:
After:
=> Removed duplicated items from alien containment list

game/state/battle/battle.cpp, game/state/battle/battleunit.cpp, game/state/battle/battleunit.h
Fixes #1394.
The mission count now increments if the agent survives the battle, not on battle load.
=> Fix mission count incrementing on load.

framework/options.cpp, framework/options.h, game/ui/general/moreoptions.cpp, game/ui/tileview/cityview.cpp
Addresses #1318.
Adds an option to show only vehicles in the current dimension or between dimensions. This option is on by default.
=> Add option to only show vehicles in current dimension.

game/ui/tileview/cityview.cpp
Fixes #1415
Yet another bug introduced in the multi select update is fixed. Non-hostile, non-owned vehicles will now appear in the hostile vehicle list. A redundant check for vehicle->tileobject was also removed.
=> Fix selected non-hostile vehicles not appearing in hostile vehicle list

game/state/gamestate.cpp
Fixes #1407.
The detection and rearm/refuel checks are both performed at 5 minute intervals. If it happens at the same time, the alertscreen wasn't allowed to fully load and was missing agent icons. Reversing the order of the checks now allows the user to take care of the alert before dismissing the refuel/rearm message.
=> Fix alertscreen agent icons not appearing.

game/ui/general/transactioncontrol.cpp
Fixes #1410.
Adds tooltip text to the buy and sell buttons. Switches if the "MarketOnRight" option is toggled. Adds "Transfer" to transfer screen buttons and "Destroy" and "Contain" to alien containment screen.
=> Add tooltip to buy and sell buttons.

game/state/city/vehicle.cpp, game/state/city/vehicle.h
Prevents passenger modules from being scrapped if the number of passengers would drop below what the vehicle could support. Prevents cargo modules from being scrapped if any cargo is on board.
Should this destroy extra cargo or passengers and add to the risk of recovery? I don't think so but it is something to think about for the future.
=> Prevent scrapping used modules.

game/ui/tileview/battleview.cpp
Addresses #1323 
This *should* fix this issue. The logic is:
If the weapon can't fire,
If the weapon isn't empty,
if the weapon is a launcher, no arc
else out of range.
This means the weapon will never display these other messages if out of ammo. Is this OG?
I find this situation difficult to test, so I can't tell if this will break other things.
=> Fix out of range message when out of ammo.

game/ui/base/transactionscreen.cpp
Fixes #1414 
Now only aliens should disappear when inactive, everything else is grayed out.
=> Fix non-bio items missing when sold out

game/state/gamestate.cpp, tools/extractors/extract_agent_equipment.cpp
Fixes #1383 (also mentioned in #608 and #1374)
- `tools/extractors/extract_agent_equipment.cpp`: agent equipment extractor is setting Brainsucker Pod store space as 16 via `tacp` / `data_t`, so here we set the correct store space of 1.
- `game/state/gamestate.cpp`: running DataExtractor updates `base_gamestate` values but it seems that this change is only reflected in new games, and older saved games have their own gamestate, is that correct? Because of that problem, it was also needed to update store space value from gamestate when reading an older savefile.
Now 1 Brainsucker Pod will account for only 5% of Alien Containment space (1/20 = 0.05)
=> Fix Brainsucker Pod store space

tools/extractors/extract_agent_equipment.cpp
Quick update to use constant reference for brainsucker launcher instead of number.
=> Updating brainsucker launcher reference to use constant

framework/options.cpp, framework/options.h, game/state/city/vehicle.cpp, game/state/city/vehicle.h, game/ui/general/moreoptions.cpp
Resolves #1312 and finishes #1405
Added optional feature that, when enabled, will add "*" prefix when displaying name of non-X-COM vehicles in alert message. Default option value is true.
Function `Vehicle::getFormattedVehicleNameForEventMessage(GameState &state)` will add prefix when option is true and when vehicle owner is not the player.
More Options view:
X-COM vehicle attacking construction vehicle:
X-COM vehicle being attacked by enemy vehicle:
=> Added optional feature to show prefix for non-XCOM vehicles

game/state/city/base.cpp, game/state/city/base.h, game/state/shared/agent.cpp, game/ui/base/aliencontainmentscreen.cpp, game/ui/base/basescreen.cpp, game/ui/base/buyandsellscreen.cpp, game/ui/base/recruitscreen.cpp, game/ui/base/transactionscreen.cpp, game/ui/base/transferscreen.cpp, game/ui/tileview/cityview.cpp
Since getUsage is returning the result of a division operation, it makes more sense the function return be float instead of int.
- Updated texts format and number comparisons to proper float type
- Added `const` and `auto` modifiers whenever possible
- Removed unnecessary `std::round` at getUsage
Obs.: as indicated by the branch name, my original idea was to convert it to double, but then I checked that all existing references to getUsage function are already using float.
=> Update getUsage type to float

game/ui/general/aequipmentsheet.cpp, game/ui/general/aequipmentsheet.h, game/ui/general/vehiclesheet.cpp, game/ui/general/vehiclesheet.h
Resolves #1429
Right now it only adds absolute value for store space. To display this information as percentage value, I will have to think a way to let the sheet view knows which screen is calling it, since the available space can come from item storage or alien containment. I guess it makes more sense to leave this for another PR in the future.
Files `aequipmentsheet.cpp` and `vehiclesheet.cpp`:
- Added store space as "Storage" in second line
- Refactored code to remove duplicated function that displayed info of unsearched items
- Updated label references for lines below Storage label
Alien Containment:
Vehicles:
Agent:
=> Add store space item info

.github/workflows/cmake.yml
We were using gcc-13 but that seems to have been removed from the 22.04 image that "ubuntu-latest" actually gave us.
May as well move to gcc-14 at the same time.
=> Move github builder to ubuntu 24.04 and gcc-14

README.md
The SDL2 package was incorrect, also I just tested these instructions on 24.04 and they work great.
=> Fix incorrect package name in readme, Tested on Ubuntu 24.04

game/state/shared/aequipment.cpp
Addresses #1445
If the ammo amount in the clip plus the ammo amount in the gun is less than the max ammo amount, the clip will be loaded in the gun instead of swapped as before and the clip will disappear. This appears to be what OG does.
=> Add partial clip refilling in battlescape

data/forms/city/debugoverlay_city.form, game/ui/tileview/cityview.cpp
Fixes #1443
Updates:
- Now unresearched UFO will display "UFO" instead of full name in hostile vehicles tab. Other vehicles name should displays without any changes
- Did some refactors in hostile vehicles tab logic
- Fixed "assault" debug typo
Before:
After:
=> Issue 1443: Hiding unresearched UFO names 

game/state/battle/battle.cpp, game/state/battle/battle.h
Fixes #1422
Now, after finishing a Base Defense battle, live aliens will be considered for score calculation, and they will NOT be send to any vehicle, but will be added to base alien storage instead.
Updates list:
- For score math, live aliens will be considered if mission is a base defense and base has alien storage **OR** if mission has player craft with available bio storage.
- Similarly, live aliens will be set as "leftover" only when **BOTH** conditions above are false.
- At `battle.cpp`, instructions inside `if (!playerVehicles.empty())` and `for (auto &v : playerVehicles)` will only be executed when mission is **NOT** a base defense one. Since both instruction groups deal with adding stuff at vehicles to be send to base, it seems that they shouldn't execute when defending a base. …
=> Live alien recovery after base defense battle

game/state/battle/battle.cpp, game/state/battle/battle.h
Fixes #1333, fixes #1422
For both alien and item loot:
- If mission is NOT base defense, then loot will be stored into vehicles
- If mission is base defense but NO storage available, again loot will be stored into vehicles
- If mission is base defense and storage is available, then loot will be stored straight into base storage
After adding a loot element into base, this loot will be removed from loot list, avoiding single loot element from being doubly added to both base and vehicle storage.
Also storage logic should be independent for each type. Example: if base defense mission has both live aliens and item loot, but only item storage available at base, then items should be stored into base, but aliens will be stored into vehicles if possible.
=> Recovering aliens and item loot after base defense mission

game/ui/base/basestage.cpp
Fixes #1444 
Inspired by conversations in #797. Admittedly I'm not exactly sure why this works, but it does. I'm updating the base screen form after the begin function since the base highlight box is part of that and not the research screen.
=> Fix red square rendering on research complete

game/ui/tileview/cityview.cpp
Fixes #1453 
When displaying the org relations, they use wording implying the orgs relations with XCOM eg: "Allied with XCOM" or "Hostile to XCOM". This leads me to believe that the relation check should take place from the perspective of the org and not XCOM. In this fix, the code was checking XCOMs relation to the org and not the other way around. This led to an edge case where Megapol had a relation of **Allied** with XCOM, but XCOM had a relation of **Friendly** with Megapol. The check for displaying the orgs in the org tab checked from XCOMs perspective while the text at the bottom checked from the orgs perspective. Both now check from the org's point of view. Apologies for the confusing wording, this was a strange issue.
- Should the relations between orgs and XCOM ever be different …
=> Fix org tab showing incorrect relations with XCOM

game/ui/general/vehiclesheet.cpp, game/ui/general/vehiclesheet.h
Partially fixes #1455
Now vehicle equipment will show "Alien Artifact" instead of name when equipment is not researched.
Also removed default value for `isResearched` parameter.
Save used: [Unresearched Alien Artifacts.zip](https://github.com/OpenApoc/OpenApoc/files/15421891/Unresearched.Alien.Artifacts.zip)
=> Removed default value for isResearched in VehicleSheet::display

game/ui/general/aequipscreen.cpp, game/ui/general/aequipscreen.h
Following with #1455, game will now inform user all the ammo types that needs to be researched together with weapon before you can be able to use it.
Also updated `tryPickUpItem` to not only return pickup result but also which item was selected.
Example where Brainsucker Launcher is researched, but Brainsucker Pod is not:
Let's say that a weapon has multiple ammo types. Warn message will properly display list of ammo types that need to be researched:
Items that are not weapon, or weapon with no ammo type will display default message. Example with Disruptor Gun:
=> Warning all weapon ammo types that needs to be researched before using

game/state/battle/battleunitmission.cpp, game/state/tilemap/tilemap.h, game/ui/tileview/battleview.cpp
Like discussed in #1326, sometimes the path calculated in TU math display and the path actually taken by an agent are no the same.
Right now, when you hover a tilemap, `findShortestPath` is called passing parameter `iterationLimit` as 1000. But when calling same function but for move order, this parameter actually gets value of `distance * PATH_ITERATION_LIMIT_MULTIPLIER`.
This PR is setting this value for both cases as 1000, since the path for TU preview is actually the correct one.
Before fix: https://www.youtube.com/watch?v=AAjcc0clThY
After fix: https://www.youtube.com/watch?v=NX0mv26-N4E
Save used: [save_blocked conveyor belt.zip](https://github.com/OpenApoc/OpenApoc/files/14387145/save_blocked.conveyor.belt.zip)
Also 1000 is now a constant in `TileMap`.
=> Using same iteration limit value for both preview and move order

forms/label.cpp, game/state/gamestate.cpp, game/state/gamestate.h, game/ui/base/buyandsellscreen.cpp, game/ui/base/recruitscreen.cpp, library/strings.cpp, library/strings.h
Fixes #1380
- Updated `fromInteger`, `fromFloat` and `fromFloat` with optional parameter to return string with currency format
- Updated `GameState::getPlayerBalance` to return balance with currency format, turned on by default
Both credit and delta credit labels are updated to display with currency format.
I tried to use some other library to format string with currency mask but couldn't find a better alternative so I had to implement it manually. If someone find a more elegante solution please let me know, I can't believe C++ doesn't have something better for that.
Next steps: add current format in other places such as "Cost to build" in base view and "Price" in buy/sell view.
=> Issue #1380: display credit labels in currency format

game/ui/base/basescreen.cpp, game/ui/base/researchselect.cpp, game/ui/city/basebuyscreen.cpp, game/ui/city/bribescreen.cpp, game/ui/city/diplomatictreatyscreen.cpp, game/ui/city/scorescreen.cpp, game/ui/city/weeklyfundingscreen.cpp, game/ui/general/transactioncontrol.cpp, game/ui/ufopaedia/ufopaediacategoryview.cpp
Following #1467, now adding credit label formatting to all text fields where its content starts with '$' char
=> Adding currency formatting to all label texts starting with dollar sign char

game/ui/general/aequipscreen.cpp, game/ui/general/transactioncontrol.cpp
When a weapon is researched, but not its ammo type, weapon name will be displayed, but game will comply about need to research ammo before using it.
If weapon is not researched, it's still displayed as Alien Artifact
Same for Buy and Sell screen:
Research topic will be searched by name, to check if it matches with weapon name. If no topic match is found, then code will use previously `item->type->canBeUsed` function - which is not the best case, since this will consider not only weapon research status but also ammo research status.
=> Showing weapon name when weapon is researched but not ammo type

game/state/rules/aequipmenttype.cpp, game/state/rules/aequipmenttype.h, game/ui/general/aequipscreen.cpp, game/ui/general/transactioncontrol.cpp
Refactoring changes made at #1472 to unify logic into single function.
Now `AEquipmentType::isResearched()` is being used to check if equipment type is already researched.
=> Refactored check if equipment type is researched

game/state/battle/battle.cpp, game/state/battle/battle.h
Like stated in #1447, #1456 and #1422, when "consider nearby vehicles" option is set to True, nearby vehicles were considered for loot pickup, but NOT for score math in `Battle::finishBattle`
- Moved to `Battle::getPlayerVehicles` code related to list all player vehicles in battle, considering if nearby vehicles are allowed to get post-battle loot.
- Updated score math in `Battle::finishBattle` to consider all player vehicles in battle, not only `state.current_battle->player_craft` like it was doing before fix
- Moved logic related to carrier presence check to `Battle::isCargoCarrierPresent` and `Battle::isBioCarrierPresent`
- Added some comments and simplified some previous logic
=> Consider nearby vehicles for score math related to loot pickup

game/state/battle/battle.cpp
Fixes #1482
Vehicles leaving a mission used to have an empty "alien artifact" item, with count zeroed.
This item is not added anymore, which means that vehicles with no loot are now empty for good.
As a consequence, the dialog "Items from tactical combat zone have arrived" now will only appear when landed vehicle really have something to unload at base, since it used to appear for every single vehicle landing.
=> Stop adding empty cargo at vehicle when exiting battle

.gitmodules, README.md, game/state/city/base.cpp
- Added magic_enum lib to dependencies. It can be used to get enum value as astring
- Updated `Base::buildFacility` and `Base::destroyFacility` to print a log warning with specific error if validation doesn't go well
=> Updating base facility error logs with magic_enum

game/state/city/vehicle.cpp
Fixes #1487
Removing incorrect `presentScenery` check at `VehicleMover::updateCrashed`
I couldn't find a situation where this update would crash, and I also used [last update done at this function](https://github.com/OpenApoc/OpenApoc/commit/e5fc6da130f8321a5789eea3bff9ad81e2ce8c5a#diff-3616dc8eea6e5f773f9434f708c2ac82234b86686e06fb238986ae3d8f8793f7R1126) as reference.
=> Removing incorrect presentScenery check at VehicleMover::updateCrashed

game/state/city/base.cpp, game/ui/base/basescreen.cpp
I realized that the logic at `Base::alienContainmentExists` is wrong and the method name is misleading right now.
Fixing logic so alien containment is True when base has alien capacity.
=> Fixing logic at Base::alienContainmentExists

game/state/city/vehicle.cpp
Addresses #1310 
I found what is causing the slow vehicle problem, but this is just a band-aid approach to fixing it.
On line 573, if ticksToMove is 1 and ticksToTurn is high (100+), the vehicle velocity will be set to a ridiculously small number. If this happens, the vehicle can be stuck moving too slowly to reach its' goal, especially if the vehicle is facing the correct direction. Since the vehicle is facing its' goal, the velocity never changes as it is set when a new goal is selected. This PR sets the minimum ticksToMove to 2, as this seems to be enough to stop the problem. Since this issue only happened on the slowest speed where ticks are set to 1, increasing the number to 2 should be enough.
Rewriting the turning speed mechanic is above my paygrade, so this should stop this …
=> Fix minimum velocity when turning

game/state/battle/battle.cpp
&player_vehicle takes the address of that in the current_battle struct, so it always non-null, and if() of that object is always true as it's comparing against that pointer not the StateRef<> object itself
=> Fix crash on battle exit

game/state/city/vehicle.cpp, game/state/city/vehicle.h
This PR should solve Issue #1130 by decoupling the slow down during turns mechanic from the game ticks. It now uses the vehicles angular velocity. This unfortunately lead to another correction value, which is purely based on data analysis. Average deviation of the Slowdown compared to the old method is about 2.5%.
@FilmBoy84 I will do the fix for Lint this weekend, I tried to work with just the command line and without IDE out of curiosity, this somehow disregarded the formatting.
=> Fix #1310 Turning Slow Down Mechanic

game/state/gamestate.cpp
Fix: when Vehicles Ordered to Attack a UFO that then returns to the alien dimension have "stuck" orders on Map
=> FIX - Attack Orders "stuck" when UFO returns to Alien Dimension #365

game/ui/base/basescreen.cpp, game/ui/base/basestage.cpp, game/ui/base/basestage.h, game/ui/base/transactionscreen.cpp, game/ui/base/transactionscreen.h
Fixes #1298 and #1392
This restores the functionality of the original game. In the transfer, buy and sell, and alien containment screens, you will be returned to the original base that was selected from the base screen. In the research screen, you will be transferred to the base you select regardless of the original selection. Not sure if this is desired but this does fix bases not being highlighted as well. If it would be better to unify the behavior for all screens, it would be an easy fix.
=> Fix BaseScreen not highlighting correct base

install/windows/installer.nsi
The version number has been broken for a while in the Windows installer, we are using a different format now. The installer now uses the commit date, number of commits, and hash. I can't properly test this, but if it fails it will still fall back to 0.0.0
Now:
Fix:
=> Update installer to correct version information

game/ui/base/basescreen.cpp
When opening the base screen and not in 640x480, the facility list is not populated until the mouse enters. This addresses this issue.
Problem:
=> Fix facilities list not populated when opened

data/forms/ufopaedia.form, game/ui/ufopaedia/ufopaediacategoryview.cpp
A value was added to the UFOpaedia screen without changing the form, causing a crash in certain situations. This adds an extra label and value for this situation.
=> Fix UFOpaedia form crash

game/state/city/base.cpp
Fixes #1516 
Scientists and engineers are now unassigned when the lab or workshop is deleted.
=> Fix scientist reassignment on lab deletion

game/state/city/vehicle.cpp, game/state/city/vehiclemission.cpp
The issue turned out to be more complex than it initially seemed. Rescue V. 77 was trying to rescue Construction V. 76, which had crashed and was located inside a building. Since it didn't have a 'tileObject,' fixing that introduced new issues. These were also resolved. However, further testing is needed to ensure that Rescue V. still functions properly.
=> FIX - setPosition called on vehicle with no tile object crash #1109

game/state/battle/battleunit.cpp
This fixes an interesting problem. 
If you kill the last alien right before a brainsucker hatches in a RT mission, the mission will end. This obviously should not happen as a hostile alien is still alive. I have even seen my units get brainsucked and the mission will still end.
This forces the game to re-check if the mission should end when a brainsucker hatches. I will include a save for ease of testing. The save is right before a brainsucker hatches and the last enemy has been killed.
[battleend.zip](https://github.com/user-attachments/files/18920594/battleend.zip)
=> Recheck mission end on brainsucker spawn

game/state/city/vehicle.cpp
I ran into a problem when testing passenger pickup. I was trying to pick up multiple agents in the city in one run, but it failed due to a currentBuilding check when not in a building. This ensures that this check will only occur when the vehicle is landed in a building.
If you try to pick up another agent while already ferrying another, it will simply ignore the request and continue to the base. This was the behavior before the alien containment check.
=> Check for alien containment at base only

game/state/city/building.cpp
As mentioned on Discord, manual pickup is not working under specific circumstances.
If CallExistingFerry is off and transtellar is hostile, you will not be able to manually pick up agents in the city. If the game is unable to spawn a ferry, the code never reaches the manual pickup section of updateCargo. This ensures the manual pickup section will always be evaluated.
=> Fix no manual pickup with CallExistingFerry option

framework/jukebox.cpp
This seems to be needed to newer MSVC, likely we were relying on transitive includes previously?
=> Build fix: Jukebox uses chrono

.github/workflows/lint.yml
The previous linter was fragile around removing files or figuring out what git refs to use, so just format *Everything* and fail if there's any changes made.
=> Format everything in the lint CI step

framework/framework.cpp
So apparently on Linux, SetRelativeMouseMode also needs to be true for the mouse grab feature to work. I can't test on MacOS so no idea if this is working there. It doesn't seem any UI interactions have been affected with this change.
=> Fix mouse grab on Linux

game/state/rules/city/vehicletype.h
Fixes #1411 
According to Wong, bikes get +4 speed. A helpful [comment](https://github.com/OpenApoc/OpenApoc/issues/1411#issuecomment-2256734991) by @acejoh pointed to all vehicles under 350 weight getting the boost. This is what I went with.
=> Add correct speed to light vehicle types

framework/options.cpp, framework/options.h, game/ui/general/moreoptions.cpp, game/ui/tileview/cityview.cpp
Vehicles are not followed when idle, same with the soldiers in vehicles. An option has been added to prevent the following of vehicles on the strategy map as per OG, off by default.
=> Don't follow vehicle when idle

data/forms/city/infiltration.form, game/state/shared/organisation.h, game/ui/city/infiltrationscreen.cpp, game/ui/city/infiltrationscreen.h, game/ui/components/controlgenerator.cpp, game/ui/components/controlgenerator.h
Addresses #1211 
Here is the updated alien infiltration screen, changes:
Org spacing isn't perfect, but pretty close. I don't think the icon size is exact either, but I used the existing cityview org icons.
There is a problem on 640 x 480 where the icons won't appear until moused over. This is an issue that has popped up before.
There is a TODO about making curved lines, that may be above my skills.
Let me know if anything else is broken.
=> Alien infiltration screen update

game/state/rules/city/vehicletype.h
I didn't realize alien craft have no engine, this meant they could not move with my change. It is fixed now. The 03162025 release is completely broken and should be destroyed.
=> Fix alien craft having 0 speed

game/state/battle/battle.cpp, game/state/battle/battle.h, game/state/gamestate.cpp, game/state/gamestate.h, game/state/gamestate_serialize.xml, game/state/rules/battle/battlemap.cpp, game/state/rules/battle/battlemap.h
A code cleanup split out of some ongoing re-work of StateRef<> stuff, shouldn't cause any functional changes - Except it'll change the save format slightly breaking saves if you have an ongoing battle
Rather than casting between string IDs and StateRef<Building> and StateRef<Vehicle> all the time just store the StateRefs directly, as typed objects tend to be less error-prone.
=> Cleanup battle location management

data/forms/aequipscreen.form, data/forms/basescreen.form, data/forms/cheatoptions.form, data/forms/city/alert.form, data/forms/city/basebuy.form, data/forms/city/baseselect.form, data/forms/city/bribe.form, data/forms/city/building.form, data/forms/city/diplomatic_treaty.form, data/forms/city/infiltration.form, data/forms/city/location.form, data/forms/city/score.form, data/forms/city/weekly_funding.form, data/forms/ingameoptions.form, data/forms/mapselector.form, data/forms/messagelog.form, data/forms/moreoptions.form, data/forms/recruitscreen.form, data/forms/researchscreen.form, data/forms/researchselect.form, data/forms/savemenu.form, data/forms/selectforces.form, data/forms/skirmish.form, data/forms/transactionscreen.form, data/forms/vequipscreen.form
=> Fix cutoff text in text_funds label

forms/label.cpp, forms/label.h, game/ui/general/aequipmentsheet.cpp, game/ui/general/aequipmentsheet.h, game/ui/general/vehiclesheet.cpp, game/ui/general/vehiclesheet.h
Addresses #1438.
This seems like the best way to handle this since we can't edit the background picture.
The name is extended below the line.
There is no way to add more horizontal room here. This would be the hard limit for characters in an item name.
Ammo can also be word wrapped.
Obviously this is designed to work with the extended weapons mod since most of the fixes apply to those weapon names. This should probably be extensively tested with every long name, I didn't get that far yet. In theory this should work for armor and everything else.
=> Allow word wrapping in item and ammo names

framework/CMakeLists.txt
This always was an internal boost detail, and seems to be removed from boost-1.89
=> Remove Boost_system dependency
